## Presentation Type Tools Explained

In [1]:
import crim_intervals
from crim_intervals import * 
from crim_intervals import main_objs
import pandas as pd
import re
import os
import numpy
import itertools
# import collections
MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)

else:
    print(MYDIR, "folder already exists.")
    
MUSDIR = ("Music_Files")
CHECK_FOLDER = os.path.isdir(MUSDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MUSDIR)
    print("created folder : ", MUSDIR)

else:
    print(MUSDIR, "folder already exists.")

saved_csv folder already exists.
Music_Files folder already exists.

In [2]:
# Select a prefix:

# prefix = 'Music_Files/'
# just add the CRIM Piece ID here
prefix = 'https://crimproject.org/mei/'
# just add the CRIM Piece ID here
mei_file = 'CRIM_Model_0008.mei'
url = prefix + mei_file
piece = importScore(url)

print(piece.metadata)

{'title': 'Ave Maria', 'composer': 'Josquin Des Prés', 'date': 1502}

# How does it Work?

### Find the Melodic Entries

With various options, then passed to the entries method:

```
nr = piece.notes(combineUnisons=True)
mel = piece.melodic(df=nr, kind='d', end=False)
mel_ng = piece.ngrams(df=mel, n=4)
entries = piece.entries(mel_ng)
ng_durs = piece.durations(df=entries)
det = piece.detailIndex(nr, offset=True, progress=True)
entries.head(15)
```


OR simply with defaults:

```
piece.entries(df=None, n=None, thematic=False, anywhere=False, fermatas=True, exclude=[])
```

In [12]:

nr = piece.notes(combineUnisons=True)
mel = piece.melodic(df=nr, kind='d', end=False)
mel_ng = piece.ngrams(df=mel, n=4)
entries = piece.entries(mel_ng)
ng_durs = piece.durations(df=entries)
det = piece.detailIndex(nr, offset=True, progress=True)
entries.fillna('').head(15)


# piece.entries()

            [Superius]            Altus            Tenor           Bassus
0.0      (4, 2, 2, -3)
16.0                      (4, 2, 2, -3)
32.0                                       (4, 2, 2, -3)
48.0                                                        (4, 2, 2, -3)
56.0   (-2, -2, -2, 2)
72.0                    (-2, -2, -2, 2)
88.0                                     (-2, -2, -2, 2)
104.0                                                     (-2, -2, -2, 2)
124.0   (2, 2, -3, -2)
156.0                                      (2, 2, -3, 3)
176.0                    (-3, -2, 2, 2)
192.0   (-3, -2, 4, 2)
200.0                                    (-3, -2, 8, -2)
216.0                                                      (-3, -2, 2, 2)
222.0  (-2, -2, -2, 2)

In [4]:
points = pd.DataFrame(columns=['Composer',
                    'Title',
                    'First_Offset',
                    'Measures_Beats',
                    'Melodic_Entry_Intervals',
                    'Offsets',
                    'Soggetti',
                    'Time_Entry_Intervals',
                    'Voices',
                    'Presentation_Type'])
points2 = pd.DataFrame()
# defines column order in final df
# others are at the end for the overlapping entries
col_order = list(points.columns) + ['Number_Entries',
                                    'Flexed_Entries',
                                    'Parallel_Entries',
                                    'Parallel_Voice',
                                    'Count_Offsets',
                                    'Offsets_Key']

det = piece.detailIndex(nr, offset=True, progress=True)
points

Empty DataFrame
Columns: [Composer, Title, First_Offset, Measures_Beats, Melodic_Entry_Intervals, Offsets, Soggetti, Time_Entry_Intervals, Voices, Presentation_Type]
Index: []

### Stack the Entries

- stack the entries as one column--in the order of their appearance
- We also rename a column to clarify that this is our 'pattern'

In [13]:

mels_stacked = entries.stack().to_frame()
mels_stacked.rename(columns =  {0:"pattern"}, inplace = True)
mels_stacked

                           pattern
0.0    [Superius]    (4, 2, 2, -3)
16.0   Altus         (4, 2, 2, -3)
32.0   Tenor         (4, 2, 2, -3)
48.0   Bassus        (4, 2, 2, -3)
56.0   [Superius]  (-2, -2, -2, 2)
...                            ...
1200.0 Tenor        (-2, -2, 2, 2)
       Bassus      (5, -2, -2, -2)
1236.0 [Superius]  (-2, -2, -2, 2)
       Tenor        (-2, 2, 2, -2)
       Bassus       (8, -4, 2, -2)

[74 rows x 1 columns]

### Edit Distances for Similar Entries

- find the edit distance, based on side-by-side comparison of melodic ngrams
- note that we can provide a 'head_flex' that allows small differences in the first interval to pass the test

In [15]:
# set the head flex:
head_flex = 1

# now use that flex in the "flexed_distance" function
dist = piece.flexed_distance(head_flex, entries)

# stack the result
dist_stack = dist.stack().to_frame()
dist_stack

                                 0
(4, 2, 2, -3)  (4, 2, 2, -3)     0
               (-2, -2, -2, 2)  19
               (2, 2, -3, -2)    8
               (2, 2, -3, 3)    13
               (-3, -2, 2, 2)   16
...                             ..
(8, -4, 2, -2) (-2, -2, 2, -2)  12
               (-3, 4, -2, -2)  23
               (-2, -2, 2, 2)   16
               (-2, 2, 2, -2)   16
               (8, -4, 2, -2)    0

[1089 rows x 1 columns]

### Body Flex

- filter body flex distances to threshold.  <2 is good

In [7]:
# set body flex
body_distance = 1

# filter the previous dataframe (which already considers the head flex)
filtered_dist_stack = dist_stack[dist_stack[0] < body_distance]

# restack these
filtered_dist = filtered_dist_stack.reset_index()
filtered_dist.rename(columns =  {'level_0':"source", 'level_1':'match'}, inplace = True)
filtered_dist.head()

            source            match  0
0    (4, 2, 2, -3)    (4, 2, 2, -3)  0
1  (-2, -2, -2, 2)  (-2, -2, -2, 2)  0
2   (2, 2, -3, -2)   (2, 2, -3, -2)  0
3    (2, 2, -3, 3)    (2, 2, -3, 3)  0
4   (-3, -2, 2, 2)   (-3, -2, 2, 2)  0

### Grouping Filtered Matches

- Group the filtered distanced patterns

In [8]:

full_list_of_matches = filtered_dist.groupby('source')['match'].apply(list).reset_index()
full_list_of_matches.head()

             source               match
0  (-2, -2, -2, -2)  [(-2, -2, -2, -2)]
1   (-2, -2, -2, 2)   [(-2, -2, -2, 2)]
2   (-2, -2, -3, 5)   [(-2, -2, -3, 5)]
3   (-2, -2, 2, -2)   [(-2, -2, 2, -2)]
4   (-2, -2, 2, -3)   [(-2, -2, 2, -3)]

### With the Matches Identified, Find the Locations and Distances Between Them

- Using the "matches" from the previous step, return a series of arrays:  all of the instances of a given soggetto, with offset and voice

In [9]:
# just decide in advance that we are not looking for hidden types.
include_hidden_types = False

# Group the filtered distanced patterns
full_list_of_matches = filtered_dist.groupby('source')['match'].apply(list).reset_index()


# classification without hidden types
if include_hidden_types == False:
    for matches in full_list_of_matches["match"]:
        
        # build a list of the related entries--
        # those that qualify as matching according to initial settings for flex head and body
        related_entry_list = mels_stacked[mels_stacked['pattern'].isin(matches)]
        entry_array = related_entry_list.reset_index(level=1).rename(columns = {'level_1': "voice", 0: "pattern"})
        offset_list = entry_array.index.to_list()
        
        # split them when we encounter a long gap (> 70 offsets)
        split_list = list(ImportedPiece._split_by_threshold(offset_list))
        
        # classify each 'set'
        # note that the melodic entry distances are determined by the helper: _temp_dict_of_details
        # the data are temporarily stored in "temp", then appended to "points" in the next steps
        for item in split_list:
            temp = piece._temp_dict_of_details(item, entry_array, det, matches)
            points = points.append(temp, ignore_index=True)
            points['Presentation_Type'] = points['Time_Entry_Intervals'].apply(ImportedPiece._classify_by_offset)
            points.drop_duplicates(subset=["First_Offset"], keep='first', inplace = True)
            points = points[points['Offsets'].apply(len) > 1]

    
    # cleaning up and recording various other features:
    # offsets
    points["Offsets_Key"] = points["Offsets"].apply(ImportedPiece._offset_joiner)
    
    # flexed entries ?
    points['Flexed_Entries'] = points["Soggetti"].apply(len) > 1
    
    # how many entries ?
    points["Number_Entries"] = points["Offsets"].apply(len)
    
    # makes sure we have no p types with only one entry
    points["Count_Offsets"] = points["Offsets"].apply(set).apply(len)
    points = points[points["Count_Offsets"] > 1]

    # sorts results by first offset
    points = points.reindex(columns=col_order).sort_values("First_Offset").reset_index(drop=True)
    
    # applying various private functions for overlapping entry tests.
    # note that ng_durs must be passed to the first of these, via args
    
    points["Entry_Durs"] = points[["Offsets", "Voices"]].apply(ImportedPiece._dur_ngram_helper, args=(ng_durs,), axis=1)
    points["Overlaps"] = points[["Entry_Durs", "Offsets"]].apply(ImportedPiece._entry_overlap_helper, axis=1)
    points["Count_Non_Overlaps"] = points["Overlaps"].apply(ImportedPiece._non_overlap_count)
    
    # remove columns no longer needed
    points.drop(['Count_Offsets', 'Offsets_Key', 'Entry_Durs', 'Overlaps'], axis=1, inplace=True)

    
points

TypeError: _temp_dict_of_details() takes 4 positional arguments but 5 were given

### Split the Lists so We Avoid Long Gaps

In [10]:
# gets Progress!

temp = points.set_index("First_Offset")
temp2 = temp
piece.di(temp2, progress=True, beat=False, measure=False)

/Users/rfreedma/opt/anaconda3/envs/encoding_music/lib/python3.9/site-packages/crim_intervals/main_objs.py:821: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ret.dropna(inplace=True, how='all')
/Users/rfreedma/opt/anaconda3/envs/encoding_music/lib/python3.9/site-packages/pandas/core/frame.py:5582: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().sort_index(

Empty DataFrame
Columns: [Composer, Title, Measures_Beats, Melodic_Entry_Intervals, Offsets, Soggetti, Time_Entry_Intervals, Voices, Presentation_Type]
Index: []