## Filtering Presentation Types

### What can you do with this Notebook?

This notebook explores some techniques for filtering the reults of the Presentation Type tool.  See the main notebook for Presentation types to review the various options.

In [1]:
import crim_intervals
from crim_intervals import * 
from crim_intervals import main_objs
import pandas as pd
import re
import os
import numpy
import itertools
from music21 import *
MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)
else:
    print(MYDIR, "folder already exists.")
    
MUSDIR = ("Music_Files")
CHECK_FOLDER = os.path.isdir(MUSDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MUSDIR)
    print("created folder : ", MUSDIR)
else:
    print(MUSDIR, "folder already exists.")

saved_csv folder already exists.
Music_Files folder already exists.

In [2]:
# from music21 import converter

# volpiano_stream = music21.converter.parse('./sample.volpiano')

# part = music21.converter.parse

In [6]:
# from music21.converter.subConverters import ConverterVolpiano

volpiano_string = '1---d--dc---f--g---f--gh--h---hkjklk--hijh7---h---gf--ghjh-hg--hg---g---g--e--g---hg7--fg---fe--c---eg--e---fe--d--d---4---h--h--g--f--gh--g7---3'
test = converter.parse('volpiano: ' + volpiano_string)

# Add metadata
test.metadata = metadata.Metadata()
test.metadata.title = 'ID123'
test.metadata.composer = 'Regensburg'

# Add part name
p = stream.Part()
p.partName = 'Cantus'
test.insert(0, p)

# Display the metadata
print(f"Title: {test.metadata.title}")
print(f"Composer: {test.metadata.composer}")
print(f"Part Name: {p.partName}")


test.write('musicxml', 'test.xml')

Title: ID123
Composer: Regensburg
Part Name: Cantus

PosixPath('/Users/rfreedma/Documents/CRIM_Python/CRIM_JHUB/test.xml')

In [11]:
piece = importScore('test.xml')
nr = piece.notes()
nr.index.rename('Index', inplace=True)
nr.rename(columns={'Part-1': 'cantus'}, inplace=True)
print(piece.metadata)
mel = piece.melodic(df = nr, kind='d')
ng = piece.ngrams(df=mel, n=4)
ng.value_counts().to_frame()

{'title': 'ID123', 'composer': 'Regensburg', 'date': None}

                 0
cantus
(-2, 2, 2, -2)   2
(-2, -2, 2, 2)   2
(1, -2, -2, 2)   2
(2, -2, 1, -2)   2
(2, 1, 1, 3)     1
(1, 5, 1, -2)    1
(2, -2, -2, -3)  1
(2, -2, -2, 1)   1
(2, -2, -2, 2)   1
(2, -2, -3, 2)   1
(2, -2, 1, 1)    1
(2, -2, 2, 2)    1
(-2, -2, -3, 3)  1
(1, 1, 3, -2)    1
(2, 2, -2, -3)   1
(2, 2, -2, 1)    1
(2, 2, 1, 1)     1
(2, 2, 2, -2)    1
(3, -2, 2, 2)    1
(3, -3, 2, -2)   1
(3, 2, -2, -2)   1
(3, 3, -3, 2)    1
(4, 2, -2, 2)    1
(1, 3, -2, 2)    1
(1, -3, 3, 2)    1
(1, 1, -3, 3)    1
(-2, 2, -2, 1)   1
(-2, -2, 2, -2)  1
(-2, -3, 2, -2)  1
(-2, -3, 3, 3)   1
(-2, 1, -2, -2)  1
(-2, 1, -2, 2)   1
(-2, 1, 1, -3)   1
(-2, 1, 5, 1)    1
(-2, 2, -2, -2)  1
(-2, 2, 2, 1)    1
(-2, -2, 1, 5)   1
(-2, 2, 2, 2)    1
(-2, 4, 2, -2)   1
(-3, 2, -2, -2)  1
(-3, 2, -2, 1)   1
(-3, 3, 2, -2)   1
(-3, 3, 3, -3)   1
(1, -2, 2, -2)   1
(1, -2, 4, 2)    1
(5, 1, -2, -2)   1

#### Load the Piece Here

* Note that you can load from CRIM, or put a file in the **Music_Files** folder in the Notebook.

In [76]:
# Select a prefix:
# prefix = 'Music_Files/'
# prefix = 'https://raw.githubusercontent.com/RichardFreedman/CRIM_Additions/main/'
prefix = 'https://crimproject.org/mei/'

# add the CRIM Piece ID here
mei_file = 'CRIM_Model_0008.mei'
url = prefix + mei_file
piece = importScore(url)

# print the details about composer and title to be sure you have loaded the correct piece
print(piece.metadata)

{'title': 'Ave Maria', 'composer': 'Josquin Des Prés', 'date': 1502}

In [78]:
piece.melodic()

       cantus Part-2 Part-3 Part-4
0.0       NaN   Rest   Rest   Rest
4.0        P4    NaN    NaN    NaN
8.0       NaN   Rest   Rest   Rest
12.0       P1    NaN    NaN    NaN
16.0       M2    NaN   Rest   Rest
...       ...    ...    ...    ...
1248.0    -M2    -m3     m2     M2
1252.0    NaN     m2    NaN    NaN
1256.0    -m2     M2     M2    -M2
1272.0     m2     P1    -M2    -P5
1288.0     P1     P1     P1     P1

[540 rows x 4 columns]

## Find Presentation Types
* `piece.presentationTypes()`

- **limit to entries** (following rests or section) = `limit_to_entries = True`.
- allowing **'moving window'** of all patterns in every voice = `limit_to_entries = False`
- set the **length of the soggetti** with `melodic_ngram_length = n`
- set **flexed threshold for first interval** `flex_threshold=1`
- set the **maximum difference between similar soggetti** with `edit_distance_threshold = n`
- to **include all the hidden PENs and IDS** (those found within longer Fugas, use `include_hidden_types = True`.  
- for faster (and simpler) listing of points of imitation **without hidden forms**, use `include_hidden_types = False`

* For example:

```
piece.presentationTypes(limit_to_entries = True,
                            body_flex = 0,
                            head_flex = 1,
                            include_hidden_types = False,
                            combine_unisons = True,
                            melodic_ngram_length = 4)
```
                       
                       
* Read the documentation:  `print(piece.presentationTypes.__doc__)`

In [4]:
p_types = piece.presentationTypes(limit_to_entries = False,
                        body_flex = 0,
                        head_flex = 1,
                        include_hidden_types = False,
                        combine_unisons = True,
                        melodic_ngram_length = 4)

In [5]:
# show the full results
pd.set_option('display.max_rows', None)
p_types

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps,Progress
0,Josquin Des Prés,Ave Maria,0.0,"[1/1.0, 3/1.0, 5/1.0, 7/1.0]","[P-8, P1, P-8]","[0.0, 16.0, 32.0, 48.0]","[(4, 2, 2, -3), (3, 2, 2, -3)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,True,False,None,0,0.000000
1,Josquin Des Prés,Ave Maria,0.0,"[1/1.0, 3/1.0, 5/1.0, 7/1.0]","[P-8, P1, P-8]","[0.0, 16.0, 32.0, 48.0]","[(4, 2, 2, -3), (3, 2, 2, -3), (2, 2, 2, -3)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,True,False,None,0,0.000000
2,Josquin Des Prés,Ave Maria,56.0,"[8/1.0, 10/1.0, 12/1.0, 14/1.0]","[P-8, P1, P-8]","[56.0, 72.0, 88.0, 104.0]","[(-2, -2, -2, 2), (-3, -2, -2, 2)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,True,False,None,3,0.043478
3,Josquin Des Prés,Ave Maria,62.0,"[8/4.0, 10/4.0, 12/4.0]","[P-8, P1]","[62.0, 78.0, 94.0]","[(-2, -2, 2, -2)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,False,False,None,2,0.048137
4,Josquin Des Prés,Ave Maria,64.0,"[9/1.0, 11/1.0, 13/1.0]","[P-8, P1]","[64.0, 80.0, 96.0]","[(-2, 2, -2, 4)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,False,False,None,2,0.049689
5,Josquin Des Prés,Ave Maria,68.0,"[9/3.0, 11/3.0, 13/3.0]","[P-8, P1]","[68.0, 84.0, 100.0]","[(2, -2, 4, -2), (3, -2, 4, -2)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,True,False,None,2,0.052795
6,Josquin Des Prés,Ave Maria,72.0,"[10/1.0, 12/1.0, 14/1.0]","[P-8, P1]","[72.0, 88.0, 104.0]","[(-2, 4, -2, -2), (-3, 4, -2, -2)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,True,False,None,2,0.055901
7,Josquin Des Prés,Ave Maria,74.0,"[10/2.0, 12/2.5, 14/2.0]","[P-8, P1]","[74.0, 91.0, 106.0]","[(4, -2, -2, 2), (3, -2, -2, 2), (5, -2, -2, 2)]","[17.0, 15.0]","[[Superius], Altus, Tenor]",FUGA,3,True,False,None,2,0.057453
8,Josquin Des Prés,Ave Maria,74.0,"[10/2.0, 12/2.5, 14/2.0]","[P-8, P1]","[74.0, 91.0, 106.0]","[(4, -2, -2, 2), (2, -2, -2, 2), (3, -2, -2, 2)]","[17.0, 15.0]","[[Superius], Altus, Tenor]",FUGA,3,True,False,None,2,0.057453
9,Josquin Des Prés,Ave Maria,74.0,"[10/2.0, 12/2.5, 14/2.0]","[P-8, P1]","[74.0, 91.0, 106.0]","[(4, -2, -2, 2), (5, -2, -2, 2)]","[17.0, 15.0]","[[Superius], Altus, Tenor]",FUGA,3,True,False,None,2,0.057453
10,Josquin Des Prés,Ave Maria,76.0,"[10/3.0, 12/3.0, 14/3.0, 14/4.0, 23/1.0, 28/1....","[P-8, P1, m-9, m9, P-8, M9]","[76.0, 92.0, 108.0, 110.0, 176.0, 216.0, 221.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[16.0, 16.0, 2.0, 66.0, 40.0, 5.0]","[[Superius], Altus, Tenor, Bassus, Altus, Bass...",FUGA,7,True,False,None,2,0.059006
11,Josquin Des Prés,Ave Maria,140.0,"[18/3.0, 19/1.0, 19/2.5, 20/4.0, 21/1.5, 27/3....","[M-3, m-2, m2, m-2, M-3, P1, M-2]","[140.0, 144.0, 147.0, 158.0, 161.0, 212.0, 216...","[(-3, -2, -2, -2), (-2, -2, -2, -2)]","[4.0, 3.0, 11.0, 3.0, 51.0, 4.0, 3.0]","[[Superius], [Superius], [Superius], [Superius...",FUGA,8,True,False,None,7,0.108696
12,Josquin Des Prés,Ave Maria,156.0,"[20/3.0, 27/2.5]",[M-3],"[156.0, 211.0]","[(6, -2, -2, -2), (5, -2, -2, -2), (4, -2, -2,...",[55.0],"[[Superius], Altus]",FUGA,2,True,False,None,1,0.121118
13,Josquin Des Prés,Ave Maria,156.0,"[20/3.0, 27/2.5]",[M-3],"[156.0, 211.0]","[(6, -2, -2, -2), (5, -2, -2, -2)]",[55.0],"[[Superius], Altus]",FUGA,2,True,False,None,1,0.121118
14,Josquin Des Prés,Ave Maria,184.0,"[24/1.0, 29/1.0]",[P-8],"[184.0, 224.0]","[(-2, 2, 2, 2), (-3, 2, 2, 2)]",[40.0],"[Altus, Bassus]",FUGA,2,True,False,None,1,0.142857
15,Josquin Des Prés,Ave Maria,188.0,"[24/3.0, 25/1.0, 31/3.0, 35/3.0]","[M2, m3, P-8]","[188.0, 192.0, 244.0, 276.0]","[(2, 2, 2, 2), (3, 2, 2, 2)]","[4.0, 52.0, 32.0]","[Altus, Altus, Altus, Bassus]",FUGA,4,True,False,None,3,0.145963
16,Josquin Des Prés,Ave Maria,195.0,"[25/2.5, 31/3.0, 32/1.0, 35/3.0, 36/1.0]","[m9, m-6, M-3, m-6]","[195.0, 244.0, 248.0, 276.0, 280.0]","[(2, 2, 2, -2)]","[49.0, 4.0, 28.0, 4.0]","[Altus, [Superius], Altus, Tenor, Bassus]",FUGA,5,False,False,None,2,0.151398
17,Josquin Des Prés,Ave Maria,196.0,"[25/3.0, 32/3.0, 36/3.0]","[M9, P-11, M-3]","[196.0, 252.0, 284.0, 284.0]","[(2, 2, -2, -2), (3, 2, -2, -2)]","[56.0, 32.0, 0.0]","[Altus, [Superius], Altus, Bassus]",FUGA,4,True,True,Tenor,2,0.152174
18,Josquin Des Prés,Ave Maria,220.0,"[28/3.0, 28/4.0]",[P8],"[220.0, 222.0]","[(-2, -2, -2, 2), (-3, -2, -2, 2)]",[2.0],"[Tenor, [Superius]]",FUGA,2,True,False,None,1,0.170807
19,Josquin Des Prés,Ave Maria,256.0,"[33/1.0, 37/1.0, 40/3.0]","[P-8, M13]","[256.0, 288.0, 316.0]","[(2, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...","[32.0, 28.0]","[Altus, Bassus, [Superius]]",FUGA,3,True,True,Tenor,2,0.198758
20,Josquin Des Prés,Ave Maria,256.0,"[33/1.0, 37/1.0, 40/3.0]","[P-8, M13]","[256.0, 288.0, 316.0]","[(2, -2, -2, -2), (3, -2, -2, -2)]","[32.0, 28.0]","[Altus, Bassus, [Superius]]",FUGA,3,True,True,Tenor,2,0.198758
21,Josquin Des Prés,Ave Maria,256.0,"[33/1.0, 37/1.0]",[P-11],"[256.0, 288.0]","[(2, -2, -2, 2), (3, -2, -2, 2)]",[32.0],"[[Superius], Altus]",FUGA,2,True,True,Tenor,0,0.198758
22,Josquin Des Prés,Ave Maria,256.0,"[33/1.0, 37/1.0]",[P-11],"[256.0, 288.0]","[(4, -2, -2, 2), (2, -2, -2, 2), (3, -2, -2, 2)]",[32.0],"[[Superius], Altus]",FUGA,2,True,True,Tenor,0,0.198758
23,Josquin Des Prés,Ave Maria,316.0,"[40/3.0, 44/3.0, 44/4.0, 46/2.0, 46/3.0, 46/4....","[P5, m-10, m6, M6, M-10, M2]","[316.0, 348.0, 350.0, 362.0, 364.0, 366.0, 402.0]","[(4, 2, 2, -3), (3, 2, 2, -3), (2, 2, 2, -3)]","[32.0, 2.0, 12.0, 2.0, 2.0, 36.0]","[Altus, [Superius], Bassus, Tenor, [Superius],...",FUGA,7,True,True,Tenor,3,0.245342
24,Josquin Des Prés,Ave Maria,316.0,"[40/3.0, 44/3.0, 44/4.0, 46/2.0, 46/3.0, 46/4....","[P5, m-10, m6, M6, M-10, M2]","[316.0, 348.0, 350.0, 362.0, 364.0, 366.0, 402.0]","[(3, 2, 2, -3), (2, 2, 2, -3)]","[32.0, 2.0, 12.0, 2.0, 2.0, 36.0]","[Altus, [Superius], Bassus, Tenor, [Superius],...",FUGA,7,True,True,Tenor,3,0.245342
25,Josquin Des Prés,Ave Maria,332.0,"[42/3.0, 50/1.0, 50/2.0, 51/1.0, 51/2.0, 51/3.0]","[P5, M6, M-7, M6, M-6]","[332.0, 392.0, 394.0, 400.0, 402.0, 404.0]","[(-4, 2, -3, 2), (-2, 2, -3, 2), (-3, 2, -3, 2)]","[60.0, 2.0, 6.0, 2.0, 2.0]","[Bassus, Bassus, Tenor, Bassus, Tenor, Bassus]",FUGA,6,True,False,None,2,0.257764
26,Josquin Des Prés,Ave Maria,340.0,"[43/3.0, 49/4.0]",[m-7],"[340.0, 390.0]","[(-2, -3, 2, 2)]",[50.0],"[[Superius], Altus]",FUGA,2,False,True,Tenor,1,0.263975
27,Josquin Des Prés,Ave Maria,344.0,"[44/1.0, 45/4.0, 46/1.0, 47/4.0, 48/1.0, 50/1.0]","[M-10, M6, m6, P-5, M6, M-9]","[344.0, 344.0, 358.0, 360.0, 374.0, 376.0, 392.0]","[(-2, 2, 2, 2), (-3, 2, 2, 2)]","[0.0, 14.0, 2.0, 14.0, 2.0, 16.0]","[[Superius], Bassus, Tenor, [Superius], Tenor,...",FUGA,7,True,True,Bassus,3,0.267081
28,Josquin Des Prés,Ave Maria,350.0,"[44/4.0, 45/1.0, 46/4.0, 47/1.0]","[M6, P-5, M6]","[350.0, 352.0, 366.0, 368.0]","[(2, 2, -3, 2)]","[2.0, 14.0, 2.0]","[Tenor, [Superius], Tenor, [Superius]]",ID,4,False,True,Bassus,1,0.271739
29,Josquin Des Prés,Ave Maria,354.0,"[45/2.0, 45/3.0, 47/2.0, 47/3.0]","[M6, P-5, m6]","[354.0, 356.0, 370.0, 372.0]","[(2, -3, 2, 2)]","[2.0, 14.0, 2.0]","[Tenor, [Superius], Tenor, [Superius]]",ID,4,False,True,Bassus,1,0.274845
30,Josquin Des Prés,Ave Maria,380.0,"[48/3.0, 48/4.0]",[P-5],"[380.0, 382.0]","[(2, 2, 2, -2)]",[2.0],"[[Superius], Tenor]",FUGA,2,False,True,Bassus,0,0.295031
31,Josquin Des Prés,Ave Maria,384.0,"[49/1.0, 49/2.0]",[P-5],"[384.0, 386.0]","[(2, 2, -2, 2)]",[2.0],"[[Superius], Tenor]",FUGA,2,False,True,Bassus,0,0.298137
32,Josquin Des Prés,Ave Maria,388.0,"[49/3.0, 49/4.0, 50/4.0, 51/1.0]","[m6, m-7, m6]","[388.0, 390.0, 398.0, 400.0]","[(2, -2, 2, -3)]","[2.0, 8.0, 2.0]","[Bassus, Tenor, Bassus, Tenor]",ID,4,False,False,None,2,0.301242
33,Josquin Des Prés,Ave Maria,392.0,"[50/1.0, 51/2.0, 58/2.5, 63/2.5]","[M-2, M-9, P-8]","[392.0, 402.0, 459.0, 499.0]","[(-2, 2, 2, -2), (-3, 2, 2, -2)]","[10.0, 57.0, 40.0]","[[Superius], [Superius], Altus, Bassus]",FUGA,4,True,False,None,2,0.304348
34,Josquin Des Prés,Ave Maria,392.0,"[50/1.0, 50/2.0, 51/1.0, 51/2.0, 51/3.0]","[M6, M-7, M6, M-6]","[392.0, 394.0, 400.0, 402.0, 404.0]","[(-2, 2, -3, 2), (-3, 2, -3, 2)]","[2.0, 6.0, 2.0, 2.0]","[Bassus, Tenor, Bassus, Tenor, Bassus]",FUGA,5,True,False,None,1,0.304348
35,Josquin Des Prés,Ave Maria,395.0,"[50/2.5, 50/3.5]",[m6],"[395.0, 397.0]","[(2, -3, 2, -2)]",[2.0],"[Bassus, Tenor]",FUGA,2,False,False,None,1,0.306677
36,Josquin Des Prés,Ave Maria,396.0,"[50/3.0, 50/4.0]",[M6],"[396.0, 398.0]","[(-3, 2, -2, 2)]",[2.0],"[Bassus, Tenor]",FUGA,2,False,False,None,1,0.307453
37,Josquin Des Prés,Ave Maria,398.0,"[50/4.0, 51/4.0, 53/2.0, 56/3.0, 57/3.0, 61/3....","[m-2, M-6, P5, m-7, M-2, m-7, P8, P8, M-7, P1,...","[398.0, 406.0, 418.0, 444.0, 452.0, 484.0, 492...","[(-2, -2, -2, 2), (-3, -2, -2, 2)]","[8.0, 12.0, 26.0, 8.0, 32.0, 8.0, 55.0, 51.0, ...","[[Superius], [Superius], Altus, [Superius], Al...",FUGA,14,True,False,None,11,0.309006
38,Josquin Des Prés,Ave Maria,401.0,"[51/1.5, 58/2.0, 63/2.0, 69/3.0]","[M-9, P-8, P8]","[401.0, 458.0, 498.0, 548.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[57.0, 40.0, 50.0]","[[Superius], Altus, Bassus, Altus]",FUGA,4,True,False,None,3,0.311335
39,Josquin Des Prés,Ave Maria,403.0,"[51/2.5, 51/3.5]",[m6],"[403.0, 405.0]","[(2, -3, 2, -3)]",[2.0],"[Bassus, Tenor]",FUGA,2,False,False,None,1,0.312888
40,Josquin Des Prés,Ave Maria,405.0,"[51/3.5, 55/4.0, 56/2.0, 60/4.0, 61/2.0]","[M9, P-5, P-4, P-5]","[405.0, 438.0, 442.0, 478.0, 482.0]","[(2, 2, -3, -2)]","[33.0, 4.0, 36.0, 4.0]","[Altus, [Superius], Altus, Tenor, Bassus]",FUGA,5,False,False,None,4,0.314441
41,Josquin Des Prés,Ave Maria,428.0,"[54/3.0, 55/1.0, 59/3.0, 60/1.0]","[P-5, P-4, P-5]","[428.0, 432.0, 468.0, 472.0]","[(4, -2, 2, 2)]","[4.0, 36.0, 4.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,False,None,3,0.332298
42,Josquin Des Prés,Ave Maria,432.0,"[55/1.0, 55/3.0, 60/1.0, 60/3.0]","[P-5, P-4, P-5]","[432.0, 436.0, 472.0, 476.0]","[(-2, 2, 2, -3)]","[4.0, 36.0, 4.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,False,None,1,0.335404
43,Josquin Des Prés,Ave Maria,440.0,"[56/1.0, 56/3.0, 61/1.0, 61/3.0]","[P-5, P-4, P-5]","[440.0, 444.0, 480.0, 484.0]","[(2, -3, -2, -2)]","[4.0, 36.0, 4.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,False,None,3,0.341615
44,Josquin Des Prés,Ave Maria,448.0,"[57/1.0, 62/1.0]",[P-8],"[448.0, 488.0]","[(-2, -2, 2, -2)]",[40.0],"[[Superius], Tenor]",FUGA,2,False,False,None,1,0.347826
45,Josquin Des Prés,Ave Maria,448.0,"[57/1.0, 62/1.0, 69/1.0, 74/2.0, 75/3.0, 84/1....","[P-8, m7, P1, M2, P1, P4, m-2, M-10, P1, m7, P...","[448.0, 488.0, 544.0, 586.0, 596.0, 664.0, 672...","[(-3, -2, -2, -2), (-2, -2, -2, -2)]","[40.0, 56.0, 42.0, 10.0, 68.0, 8.0, 4.0, 28.0,...","[Altus, Bassus, Altus, Tenor, Tenor, Altus, [S...",FUGA,28,True,False,None,20,0.347826
46,Josquin Des Prés,Ave Maria,454.0,"[57/4.0, 62/4.0]",[P-8],"[454.0, 494.0]","[(-2, 2, -2, 4)]",[40.0],"[[Superius], Tenor]",FUGA,2,False,False,None,1,0.352484
47,Josquin Des Prés,Ave Maria,455.0,"[57/4.5, 62/4.5]",[P-8],"[455.0, 495.0]","[(2, -2, 4, -2), (3, -2, 4, -2)]",[40.0],"[[Superius], Tenor]",FUGA,2,True,False,None,1,0.353261
48,Josquin Des Prés,Ave Maria,462.0,"[58/4.0, 63/4.0]",[P-8],"[462.0, 502.0]","[(-2, 4, -2, 2)]",[40.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.358696
49,Josquin Des Prés,Ave Maria,508.0,"[64/3.0, 66/3.0, 67/3.0, 69/3.0, 70/3.0, 73/3.0]","[P-5, P-4, P-5, P4, M9]","[508.0, 524.0, 532.0, 548.0, 556.0, 580.0]","[(2, -3, 2, -3)]","[16.0, 8.0, 16.0, 8.0, 24.0]","[[Superius], Altus, Tenor, Bassus, Altus, [Sup...",FUGA,6,False,True,Bassus,5,0.394410
50,Josquin Des Prés,Ave Maria,512.0,"[65/1.0, 67/1.0, 68/1.0, 70/1.0, 74/1.0]","[P-5, P-4, P-5, P1]","[512.0, 528.0, 536.0, 552.0, 584.0]","[(-4, 2, -3, 2), (-3, 2, -3, 2), (-5, 2, -3, 2)]","[16.0, 8.0, 16.0, 32.0]","[[Superius], Altus, Tenor, Bassus, Bassus]",FUGA,5,True,False,None,4,0.397516
51,Josquin Des Prés,Ave Maria,512.0,"[65/1.0, 67/1.0, 68/1.0, 70/1.0, 73/1.0, 74/1.0]","[P-5, P-4, P-5, P12, P-12]","[512.0, 528.0, 536.0, 552.0, 576.0, 584.0]","[(-4, 2, -3, 2), (-2, 2, -3, 2), (-3, 2, -3, 2)]","[16.0, 8.0, 16.0, 24.0, 8.0]","[[Superius], Altus, Tenor, Bassus, [Superius],...",FUGA,6,True,False,None,5,0.397516
52,Josquin Des Prés,Ave Maria,512.0,"[65/1.0, 67/1.0, 68/1.0, 70/1.0, 73/1.0, 74/1.0]","[P-5, P-4, P-5, P12, P-12]","[512.0, 528.0, 536.0, 552.0, 576.0, 584.0]","[(-2, 2, -3, 2), (-3, 2, -3, 2)]","[16.0, 8.0, 16.0, 24.0, 8.0]","[[Superius], Altus, Tenor, Bassus, [Superius],...",FUGA,6,True,False,None,5,0.397516
53,Josquin Des Prés,Ave Maria,516.0,"[65/3.0, 67/3.0, 68/3.0, 70/3.0, 78/1.0, 81/1.0]","[P-5, P-4, P-5, P12, P-8]","[516.0, 532.0, 540.0, 556.0, 616.0, 640.0]","[(2, -3, 2, -2)]","[16.0, 8.0, 16.0, 60.0, 24.0]","[[Superius], Altus, Tenor, Bassus, [Superius],...",FUGA,6,False,False,None,5,0.400621
54,Josquin Des Prés,Ave Maria,520.0,"[66/1.0, 68/1.0, 69/1.0, 71/1.0, 73/4.0, 79/1....","[P-5, P-4, P-5, P8, P5, P-8, M2]","[520.0, 536.0, 544.0, 560.0, 582.0, 624.0, 648...","[(-3, 2, -2, -2), (-2, 2, -2, -2)]","[16.0, 8.0, 16.0, 22.0, 42.0, 24.0, 33.0]","[[Superius], Altus, Tenor, Bassus, Tenor, [Sup...",FUGA,8,True,False,None,7,0.403727
55,Josquin Des Prés,Ave Maria,524.0,"[66/3.0, 68/3.0, 69/3.0, 71/3.0, 74/1.0, 75/1....","[P-5, P-4, P-5, P8, P5, P1, P-8, P8, M-6, P1, ...","[524.0, 540.0, 548.0, 564.0, 584.0, 593.0, 628...","[(2, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...","[16.0, 8.0, 16.0, 20.0, 9.0, 35.0, 24.0, 12.0,...","[[Superius], Altus, Tenor, Bassus, Tenor, [Sup...",FUGA,24,True,True,Tenor,19,0.406832
56,Josquin Des Prés,Ave Maria,524.0,"[66/3.0, 68/3.0, 69/3.0, 71/3.0, 74/1.0, 79/3....","[P-5, P-4, P-5, P8, P5, P-8, P8, M-6, P1, M2, P1]","[524.0, 540.0, 548.0, 564.0, 584.0, 628.0, 652...","[(2, -2, -2, -2), (3, -2, -2, -2)]","[16.0, 8.0, 16.0, 20.0, 44.0, 24.0, 12.0, 44.0...","[[Superius], Altus, Tenor, Bassus, Tenor, [Sup...",FUGA,12,True,False,None,8,0.406832
57,Josquin Des Prés,Ave Maria,566.0,"[71/4.0, 72/1.0]",[P-5],"[566.0, 568.0]","[(-3, -2, -2, 5), (-2, -2, -2, 5)]",[2.0],"[Altus, Bassus]",FUGA,2,True,False,None,0,0.439441
58,Josquin Des Prés,Ave Maria,616.0,"[78/1.0, 81/1.0]",[P-8],"[616.0, 640.0]","[(5, 2, -2, -2)]",[24.0],"[Altus, Bassus]",FUGA,2,False,False,None,1,0.478261
59,Josquin Des Prés,Ave Maria,624.0,"[79/1.0, 82/1.0, 85/3.0]","[P-8, P5]","[624.0, 648.0, 676.0]","[(4, -2, -2, 2), (2, -2, -2, 2), (3, -2, -2, 2)]","[24.0, 28.0]","[Altus, Bassus, Altus]",FUGA,3,True,False,None,0,0.484472
60,Josquin Des Prés,Ave Maria,624.0,"[79/1.0, 82/1.0, 85/3.0]","[P-8, P5]","[624.0, 648.0, 676.0]","[(2, -2, -2, 2), (3, -2, -2, 2)]","[24.0, 28.0]","[Altus, Bassus, Altus]",FUGA,3,True,False,None,0,0.484472
61,Josquin Des Prés,Ave Maria,700.0,"[88/3.0, 89/3.0, 90/3.0]","[M9, M-9]","[700.0, 708.0, 716.0]","[(5, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...","[8.0, 8.0]","[Bassus, Tenor, Bassus]",PEN,3,True,False,None,2,0.543478
62,Josquin Des Prés,Ave Maria,700.0,"[88/3.0, 91/4.5]",[M-9],"[700.0, 727.0]","[(-2, 3, -2, -2)]",[27.0],"[Tenor, Bassus]",FUGA,2,False,False,None,1,0.543478
63,Josquin Des Prés,Ave Maria,796.0,"[98/1.0, 98/2.0]",[P-5],"[796.0, 800.0]","[(2, 2, -3, 4)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.618012
64,Josquin Des Prés,Ave Maria,808.0,"[99/1.0, 99/2.0]",[P-5],"[808.0, 812.0]","[(2, -3, 4, -3)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.627329
65,Josquin Des Prés,Ave Maria,820.0,"[100/1.0, 100/2.0]",[P-5],"[820.0, 824.0]","[(-3, 4, -3, 4)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.636646
66,Josquin Des Prés,Ave Maria,832.0,"[101/1.0, 101/2.0]",[P-5],"[832.0, 836.0]","[(4, -3, 4, -2)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.645963
67,Josquin Des Prés,Ave Maria,832.0,"[101/1.0, 105/2.0]",[P1],"[832.0, 884.0]","[(5, 2, -3, 2), (4, 2, -3, 2)]",[52.0],"[Altus, Tenor]",FUGA,2,True,False,None,1,0.645963
68,Josquin Des Prés,Ave Maria,844.0,"[102/1.0, 102/2.0]",[P-5],"[844.0, 848.0]","[(-2, 4, -2, -2), (-3, 4, -2, -2)]",[4.0],"[[Superius], Tenor]",FUGA,2,True,False,None,0,0.655280
69,Josquin Des Prés,Ave Maria,856.0,"[103/1.0, 103/2.0]",[P-5],"[856.0, 860.0]","[(5, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...",[4.0],"[[Superius], Tenor]",FUGA,2,True,False,None,0,0.664596
70,Josquin Des Prés,Ave Maria,856.0,"[103/1.0, 103/2.0]",[P-5],"[856.0, 860.0]","[(6, -2, -2, -2), (5, -2, -2, -2), (4, -2, -2,...",[4.0],"[[Superius], Tenor]",FUGA,2,True,False,None,0,0.664596
71,Josquin Des Prés,Ave Maria,874.0,"[104/2.5, 104/3.5]",[P-5],"[874.0, 878.0]","[(-2, -2, -2, 4)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,False,None,1,0.678571
72,Josquin Des Prés,Ave Maria,876.0,"[104/3.0, 105/1.0]",[P-5],"[876.0, 880.0]","[(-3, -2, 4, 2), (-2, -2, 4, 2)]",[4.0],"[[Superius], Tenor]",FUGA,2,True,False,None,1,0.680124
73,Josquin Des Prés,Ave Maria,888.0,"[105/3.0, 111/1.0, 114/1.0, 116/2.0, 117/1.0, ...","[P5, m-3, M-7, m-2, m10, m-3, M-7, m-2]","[888.0, 944.0, 968.0, 986.0, 992.0, 1008.0, 10...","[(2, -2, -2, -2), (3, -2, -2, -2)]","[56.0, 24.0, 18.0, 6.0, 16.0, 24.0, 18.0, 6.0]","[Altus, [Superius], [Superius], Altus, Tenor, ...",FUGA,9,True,True,Tenor,8,0.689441
74,Josquin Des Prés,Ave Maria,892.0,"[106/1.0, 106/2.0]",[m6],"[892.0, 896.0]","[(2, -3, 2, -3)]",[4.0],"[Bassus, Tenor]",FUGA,2,False,False,None,0,0.692547
75,Josquin Des Prés,Ave Maria,904.0,"[107/1.0, 107/2.0]",[P4],"[904.0, 908.0]","[(-3, 2, -3, -2), (-2, 2, -3, -2)]",[4.0],"[Altus, Tenor]",FUGA,2,True,False,None,1,0.701863
76,Josquin Des Prés,Ave Maria,960.0,"[113/1.0, 116/1.0, 121/1.0, 124/1.0]","[P-8, P8, P-8]","[960.0, 984.0, 1024.0, 1048.0]","[(-2, -2, -2, 3)]","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,False,None,3,0.745342
77,Josquin Des Prés,Ave Maria,966.0,"[113/4.0, 116/4.0, 121/4.0, 124/4.0]","[P-8, P8, P-8]","[966.0, 990.0, 1030.0, 1054.0]","[(-2, -2, 3, -2)]","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,False,None,3,0.750000
78,Josquin Des Prés,Ave Maria,967.0,"[113/4.5, 116/4.5, 121/4.5, 124/4.5]","[P-8, P8, P-8]","[967.0, 991.0, 1031.0, 1055.0]","[(-2, 3, -2, -2)]","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,False,None,3,0.750776
79,Josquin Des Prés,Ave Maria,968.0,"[114/1.0, 117/1.0, 122/1.0, 125/1.0]","[P-8, P8, P-8]","[968.0, 992.0, 1032.0, 1056.0]","[(5, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,True,False,None,3,0.751553
80,Josquin Des Prés,Ave Maria,980.0,"[115/3.0, 123/3.0, 127/3.0, 129/3.0]","[P1, m7, P-8]","[980.0, 1044.0, 1076.0, 1092.0]","[(2, 2, 2, -2)]","[64.0, 32.0, 16.0]","[Altus, Altus, [Superius], Tenor]",FUGA,4,False,False,None,3,0.760870
81,Josquin Des Prés,Ave Maria,992.0,"[117/1.0, 125/1.0, 130/2.5, 138/3.5, 143/1.0]","[P1, m-3, m3, P4]","[992.0, 1056.0, 1099.0, 1165.0, 1200.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[64.0, 43.0, 66.0, 35.0]","[Bassus, Bassus, Bassus, Bassus, Tenor]",FUGA,5,True,False,None,4,0.770186
82,Josquin Des Prés,Ave Maria,999.0,"[117/4.5, 125/4.5, 128/1.0, 130/1.0]","[P1, P11, P-8]","[999.0, 1063.0, 1080.0, 1096.0]","[(2, 2, -2, 2)]","[64.0, 17.0, 16.0]","[Bassus, Bassus, [Superius], Tenor]",FUGA,4,False,False,None,2,0.775621
83,Josquin Des Prés,Ave Maria,1080.0,"[128/1.0, 134/3.0, 137/3.0, 139/2.0]","[M6, P-8, m-3]","[1080.0, 1132.0, 1156.0, 1170.0]","[(-3, 2, -2, -2), (-2, 2, -2, -2)]","[52.0, 24.0, 14.0]","[Altus, [Superius], Tenor, Altus]",FUGA,4,True,True,Bassus,3,0.838509
84,Josquin Des Prés,Ave Maria,1082.0,"[128/2.0, 135/1.0, 138/1.0, 139/3.0]","[m7, P-8, P-4]","[1082.0, 1136.0, 1160.0, 1172.0]","[(4, -2, -2, 2), (2, -2, -2, 2), (3, -2, -2, 2)]","[54.0, 24.0, 12.0]","[Altus, [Superius], Tenor, Altus]",FUGA,4,True,False,None,1,0.840062

In [7]:
tuple_to_match = ('4', '2', '2', '-3')
filtered_df = p_types[p_types['Soggetti'].apply(lambda x: tuple_to_match in x)]
filtered_df

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps,Progress
0,Josquin Des Prés,Ave Maria,0.0,"[1/1.0, 3/1.0, 5/1.0, 7/1.0]","[P-8, P1, P-8]","[0.0, 16.0, 32.0, 48.0]","[(4, 2, 2, -3), (3, 2, 2, -3)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,True,False,None,0,0.000000
1,Josquin Des Prés,Ave Maria,0.0,"[1/1.0, 3/1.0, 5/1.0, 7/1.0]","[P-8, P1, P-8]","[0.0, 16.0, 32.0, 48.0]","[(4, 2, 2, -3), (3, 2, 2, -3), (2, 2, 2, -3)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,True,False,None,0,0.000000
23,Josquin Des Prés,Ave Maria,316.0,"[40/3.0, 44/3.0, 44/4.0, 46/2.0, 46/3.0, 46/4....","[P5, m-10, m6, M6, M-10, M2]","[316.0, 348.0, 350.0, 362.0, 364.0, 366.0, 402.0]","[(4, 2, 2, -3), (3, 2, 2, -3), (2, 2, 2, -3)]","[32.0, 2.0, 12.0, 2.0, 2.0, 36.0]","[Altus, [Superius], Bassus, Tenor, [Superius],...",FUGA,7,True,True,Tenor,3,0.245342

## Filtering the Results

Pandas offers many ways to filter any dataframe.  One of the simplest involves checking a single column for exact or partial matches..

**Exact Match the Full Contents of a Cell.** For this we use the Python method `isin(['My_Exact_Pattern'])`, which returns `True` for any row in which the given columns is an **exact match** of the given string.  If you run the following in a cell, you will see a long Series of True or False values.

```
p_types["Presentation_Type"].isin(['PEN'])
```
    
We can in turn use this **Boolean Series** to "mask" the entire dataframe to show either all the rows for which the condition is True or False (and so we could show all the PEN's, or everything *except* the PEN's.
    
```p_types[p_types["Presentation_Type"].isin(['PEN'])]
```
    
NOT the PENs includes the "~" to reverse the True and False values:
    
```
p_types[~p_types["Presentation_Type"].isin(['PEN'])]
```

You can in fact pass several possible values in this way.  But whether you are searching for one or more strings, they must be presented in the form of a Python **list**:  `['My_Exact_Pattern_1', 'My_Exact_Pattern_2']`.  For instance, we could  look for either **PEN or ID**:
    
```
p_types[p_types["Presentation_Type"].isin(['PEN', 'ID'])]
```
    
Finally, note that a **partial match** would return no results:
    
```
p_types[p_types["Presentation_Type"].isin(['P'])]
```


**Partial Match of Characters** is possible with `str.contains` method.  This returns `True` for any row in which our search pattern is *contained anywhere in the given cell*.  We could find any row in which the column "Presentation Type" contains "P" *anywhere, and not just a complete exact match*:

```
p_types[p_types["Presentation_Type"].str.contains("P")]
```
    
In practice it's useful to give such searches a name of their own, and to make a `.copy()` of the dataframe so that you don't disturb the original results:
    
```
pens_only = p_types[p_types["Presentation_Type"].str.contains("P")].copy()
```

Of course it would be more interesting to search for substrings in something like the Melodic Intervals column (which have various sets of values where we might want to know which patterns contain a M3 in the midst of some other series of entries).  But for this we need to manage the data types (see below).
    
**Comparisons:  < or >** can be useful for Fuga, as when you might want to find all the Fugas longer (or shorter) than a certain size. This code, for instance, will return a Boolean Series (True/False) of the column for Number_Entries:

```
p_types['Number_Entries'] < 4
```
    
   
We can in turn use this to 'mask' the p_types dataframe itself (notice the two sets of brackets):

```
p_types[p_types['Number_Entries'] < 4]
```

Or the opposite of the Boolean Series, so that we now have all the Fugas *not* less than 4:

```p_types[~p_types['Number_Entries'] < 4]
```

In [1]:
# Try things yourself!
p_types[p_types["Presentation_Type"].str.contains("ID")]

NameError: name 'p_types' is not defined

In [7]:
p_types[p_types['Number_Entries'] > 4]

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps
7,Josquin Des Prés,Ave Maria,76.0,"[10/3.0, 12/3.0, 14/3.0, 14/4.0, 23/1.0, 28/1....","[P-8, P1, m-9, m9, P-8, M9]","[76.0, 92.0, 108.0, 110.0, 176.0, 216.0, 221.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[16.0, 16.0, 2.0, 66.0, 40.0, 5.0]","[[Superius], Altus, Tenor, Bassus, Altus, Bass...",FUGA,7,True,0.0,None,2
8,Josquin Des Prés,Ave Maria,140.0,"[18/3.0, 19/1.0, 19/2.5, 20/4.0, 21/1.5, 27/3....","[M-3, m-2, m2, m-2, M-3, P1, M-2]","[140.0, 144.0, 147.0, 158.0, 161.0, 212.0, 216...","[(-3, -2, -2, -2), (-2, -2, -2, -2)]","[4.0, 3.0, 11.0, 3.0, 51.0, 4.0, 3.0]","[[Superius], [Superius], [Superius], [Superius...",FUGA,8,True,0.0,None,7
12,Josquin Des Prés,Ave Maria,195.0,"[25/2.5, 31/3.0, 32/1.0, 35/3.0, 36/1.0]","[m9, m-6, M-3, m-6]","[195.0, 244.0, 248.0, 276.0, 280.0]","[(2, 2, 2, -2)]","[49.0, 4.0, 28.0, 4.0]","[Altus, [Superius], Altus, Tenor, Bassus]",FUGA,5,False,0.0,None,2
16,Josquin Des Prés,Ave Maria,316.0,"[40/3.0, 44/3.0, 44/4.0, 46/2.0, 46/3.0, 46/4....","[P5, m-10, m6, M6, M-10, M2]","[316.0, 348.0, 350.0, 362.0, 364.0, 366.0, 402.0]","[(3, 2, 2, -3), (2, 2, 2, -3)]","[32.0, 2.0, 12.0, 2.0, 2.0, 36.0]","[Altus, [Superius], Bassus, Tenor, [Superius],...",FUGA,7,True,1.0,Tenor,3
17,Josquin Des Prés,Ave Maria,332.0,"[42/3.0, 50/1.0, 50/2.0, 51/1.0, 51/2.0, 51/3.0]","[P5, M6, M-7, M6, M-6]","[332.0, 392.0, 394.0, 400.0, 402.0, 404.0]","[(-4, 2, -3, 2), (-2, 2, -3, 2), (-3, 2, -3, 2)]","[60.0, 2.0, 6.0, 2.0, 2.0]","[Bassus, Bassus, Tenor, Bassus, Tenor, Bassus]",FUGA,6,True,0.0,None,2
19,Josquin Des Prés,Ave Maria,344.0,"[44/1.0, 45/4.0, 46/1.0, 47/4.0, 48/1.0, 50/1.0]","[M-10, M6, m6, P-5, M6, M-9]","[344.0, 344.0, 358.0, 360.0, 374.0, 376.0, 392.0]","[(-2, 2, 2, 2), (-3, 2, 2, 2)]","[0.0, 14.0, 2.0, 14.0, 2.0, 16.0]","[[Superius], Bassus, Tenor, [Superius], Tenor,...",FUGA,7,True,1.0,Bassus,3
27,Josquin Des Prés,Ave Maria,392.0,"[50/1.0, 50/2.0, 51/1.0, 51/2.0, 51/3.0]","[M6, M-7, M6, M-6]","[392.0, 394.0, 400.0, 402.0, 404.0]","[(-2, 2, -3, 2), (-3, 2, -3, 2)]","[2.0, 6.0, 2.0, 2.0]","[Bassus, Tenor, Bassus, Tenor, Bassus]",FUGA,5,True,0.0,None,1
30,Josquin Des Prés,Ave Maria,398.0,"[50/4.0, 51/4.0, 53/2.0, 56/3.0, 57/3.0, 61/3....","[m-2, M-6, P5, m-7, M-2, m-7, P8, P8, M-7, P1,...","[398.0, 406.0, 418.0, 444.0, 452.0, 484.0, 492...","[(-2, -2, -2, 2), (-3, -2, -2, 2)]","[8.0, 12.0, 26.0, 8.0, 32.0, 8.0, 55.0, 51.0, ...","[[Superius], [Superius], Altus, [Superius], Al...",FUGA,14,True,0.0,None,11
33,Josquin Des Prés,Ave Maria,405.0,"[51/3.5, 55/4.0, 56/2.0, 60/4.0, 61/2.0]","[M9, P-5, P-4, P-5]","[405.0, 438.0, 442.0, 478.0, 482.0]","[(2, 2, -3, -2)]","[33.0, 4.0, 36.0, 4.0]","[Altus, [Superius], Altus, Tenor, Bassus]",FUGA,5,False,0.0,None,4
37,Josquin Des Prés,Ave Maria,448.0,"[57/1.0, 62/1.0, 69/1.0, 74/2.0, 75/3.0, 84/1....","[P-8, m7, P1, M2, P1, P4, m-2, M-10, P1, m7, P...","[448.0, 488.0, 544.0, 586.0, 596.0, 664.0, 672...","[(-3, -2, -2, -2), (-2, -2, -2, -2)]","[40.0, 56.0, 42.0, 10.0, 68.0, 8.0, 4.0, 28.0,...","[Altus, Bassus, Altus, Tenor, Tenor, Altus, [S...",FUGA,28,True,0.0,None,20
41,Josquin Des Prés,Ave Maria,508.0,"[64/3.0, 66/3.0, 67/3.0, 69/3.0, 70/3.0, 73/3.0]","[P-5, P-4, P-5, P4, M9]","[508.0, 524.0, 532.0, 548.0, 556.0, 580.0]","[(2, -3, 2, -3)]","[16.0, 8.0, 16.0, 8.0, 24.0]","[[Superius], Altus, Tenor, Bassus, Altus, [Sup...",FUGA,6,False,1.0,Bassus,5
42,Josquin Des Prés,Ave Maria,512.0,"[65/1.0, 67/1.0, 68/1.0, 70/1.0, 73/1.0, 74/1.0]","[P-5, P-4, P-5, P12, P-12]","[512.0, 528.0, 536.0, 552.0, 576.0, 584.0]","[(-2, 2, -3, 2), (-3, 2, -3, 2)]","[16.0, 8.0, 16.0, 24.0, 8.0]","[[Superius], Altus, Tenor, Bassus, [Superius],...",FUGA,6,True,0.0,None,5
43,Josquin Des Prés,Ave Maria,516.0,"[65/3.0, 67/3.0, 68/3.0, 70/3.0, 78/1.0, 81/1.0]","[P-5, P-4, P-5, P12, P-8]","[516.0, 532.0, 540.0, 556.0, 616.0, 640.0]","[(2, -3, 2, -2)]","[16.0, 8.0, 16.0, 60.0, 24.0]","[[Superius], Altus, Tenor, Bassus, [Superius],...",FUGA,6,False,0.0,None,5
44,Josquin Des Prés,Ave Maria,520.0,"[66/1.0, 68/1.0, 69/1.0, 71/1.0, 73/4.0, 79/1....","[P-5, P-4, P-5, P8, P5, P-8, M2]","[520.0, 536.0, 544.0, 560.0, 582.0, 624.0, 648...","[(-3, 2, -2, -2), (-2, 2, -2, -2)]","[16.0, 8.0, 16.0, 22.0, 42.0, 24.0, 33.0]","[[Superius], Altus, Tenor, Bassus, Tenor, [Sup...",FUGA,8,True,0.0,None,7
45,Josquin Des Prés,Ave Maria,524.0,"[66/3.0, 68/3.0, 69/3.0, 71/3.0, 74/1.0, 79/3....","[P-5, P-4, P-5, P8, P5, P-8, P8, M-6, P1, M2, P1]","[524.0, 540.0, 548.0, 564.0, 584.0, 628.0, 652...","[(2, -2, -2, -2), (3, -2, -2, -2)]","[16.0, 8.0, 16.0, 20.0, 44.0, 24.0, 12.0, 44.0...","[[Superius], Altus, Tenor, Bassus, Tenor, [Sup...",FUGA,12,True,0.0,None,8
60,Josquin Des Prés,Ave Maria,888.0,"[105/3.0, 111/1.0, 114/1.0, 116/2.0, 117/1.0, ...","[P5, m-3, M-7, m-2, m10, m-3, M-7, m-2]","[888.0, 944.0, 968.0, 986.0, 992.0, 1008.0, 10...","[(2, -2, -2, -2), (3, -2, -2, -2)]","[56.0, 24.0, 18.0, 6.0, 16.0, 24.0, 18.0, 6.0]","[Altus, [Superius], [Superius], Altus, Tenor, ...",FUGA,9,True,1.0,Tenor,8
72,Josquin Des Prés,Ave Maria,992.0,"[117/1.0, 125/1.0, 130/2.5, 138/3.5, 143/1.0]","[P1, m-3, m3, P4]","[992.0, 1056.0, 1099.0, 1165.0, 1200.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[64.0, 43.0, 66.0, 35.0]","[Bassus, Bassus, Bassus, Bassus, Tenor]",FUGA,5,True,0.0,None,4
80,Josquin Des Prés,Ave Maria,1096.0,"[130/1.0, 132/1.5, 135/3.5, 137/4.0, 138/2.0, ...","[M6, M2, m3, m-7, M-3, M14]","[1096.0, 1113.0, 1141.0, 1158.0, 1162.0, 1174....","[(-2, -2, -2, 2), (-3, -2, -2, 2)]","[17.0, 28.0, 17.0, 4.0, 12.0, 62.0]","[Bassus, Altus, Altus, Altus, Bassus, Bassus, ...",FUGA,7,True,0.0,None,6

### Different Data Types Require Different Methods

Some fields (like composer or title) are simply **strings** of characters.  But the data in **Melodic_Entry_Intervals** (for instance) are **lists**, and as such we need to convert these to **strings** before we can search within them.

This is done by **applying a function** to all items in the column.  Here we **map** each item in the list to a 'string', then join those strings together as a single string, and update the column accordingly:

```
p_types["Melodic_Entry_Intervals"] = p_types["Melodic_Entry_Intervals"].apply(lambda x: ', '.join(map(str, x))).copy()
```

Now we can use `str.contains()` to find subpatterns within the Melodic Entry Intervals:

```
patterns_with_5 = p_types[p_types["Melodic_Entry_Intervals"].str.contains("5")].copy()
```

And now it is also possible to **count the values of the sets of entries** as strings:

```
p_types["Melodic_Entry_Intervals"].value_counts().to_frame()
```

In [8]:
p_types["Melodic_Entry_Intervals"] = p_types["Melodic_Entry_Intervals"].apply(lambda x: ', '.join(map(str, x))).copy()

In [9]:
p_types

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps
0,Josquin Des Prés,Ave Maria,0.0,"[1/1.0, 3/1.0, 5/1.0, 7/1.0]","P-8, P1, P-8","[0.0, 16.0, 32.0, 48.0]","[(4, 2, 2, -3), (3, 2, 2, -3), (2, 2, 2, -3)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,True,0.0,None,0
1,Josquin Des Prés,Ave Maria,56.0,"[8/1.0, 10/1.0, 12/1.0, 14/1.0]","P-8, P1, P-8","[56.0, 72.0, 88.0, 104.0]","[(-2, -2, -2, 2), (-3, -2, -2, 2)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,True,0.0,None,3
2,Josquin Des Prés,Ave Maria,62.0,"[8/4.0, 10/4.0, 12/4.0]","P-8, P1","[62.0, 78.0, 94.0]","[(-2, -2, 2, -2)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,False,0.0,None,2
3,Josquin Des Prés,Ave Maria,64.0,"[9/1.0, 11/1.0, 13/1.0]","P-8, P1","[64.0, 80.0, 96.0]","[(-2, 2, -2, 4)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,False,0.0,None,2
4,Josquin Des Prés,Ave Maria,68.0,"[9/3.0, 11/3.0, 13/3.0]","P-8, P1","[68.0, 84.0, 100.0]","[(2, -2, 4, -2), (3, -2, 4, -2)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,True,0.0,None,2
5,Josquin Des Prés,Ave Maria,72.0,"[10/1.0, 12/1.0, 14/1.0]","P-8, P1","[72.0, 88.0, 104.0]","[(-2, 4, -2, -2), (-3, 4, -2, -2)]","[16.0, 16.0]","[[Superius], Altus, Tenor]",PEN,3,True,0.0,None,2
6,Josquin Des Prés,Ave Maria,74.0,"[10/2.0, 12/2.5, 14/2.0]","P-8, P1","[74.0, 91.0, 106.0]","[(4, -2, -2, 2), (2, -2, -2, 2), (3, -2, -2, 2)]","[17.0, 15.0]","[[Superius], Altus, Tenor]",FUGA,3,True,0.0,None,2
7,Josquin Des Prés,Ave Maria,76.0,"[10/3.0, 12/3.0, 14/3.0, 14/4.0, 23/1.0, 28/1....","P-8, P1, m-9, m9, P-8, M9","[76.0, 92.0, 108.0, 110.0, 176.0, 216.0, 221.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[16.0, 16.0, 2.0, 66.0, 40.0, 5.0]","[[Superius], Altus, Tenor, Bassus, Altus, Bass...",FUGA,7,True,0.0,None,2
8,Josquin Des Prés,Ave Maria,140.0,"[18/3.0, 19/1.0, 19/2.5, 20/4.0, 21/1.5, 27/3....","M-3, m-2, m2, m-2, M-3, P1, M-2","[140.0, 144.0, 147.0, 158.0, 161.0, 212.0, 216...","[(-3, -2, -2, -2), (-2, -2, -2, -2)]","[4.0, 3.0, 11.0, 3.0, 51.0, 4.0, 3.0]","[[Superius], [Superius], [Superius], [Superius...",FUGA,8,True,0.0,None,7
9,Josquin Des Prés,Ave Maria,156.0,"[20/3.0, 27/2.5]",M-3,"[156.0, 211.0]","[(6, -2, -2, -2), (5, -2, -2, -2), (4, -2, -2,...",[55.0],"[[Superius], Altus]",FUGA,2,True,0.0,None,1
10,Josquin Des Prés,Ave Maria,184.0,"[24/1.0, 29/1.0]",P-8,"[184.0, 224.0]","[(-2, 2, 2, 2), (-3, 2, 2, 2)]",[40.0],"[Altus, Bassus]",FUGA,2,True,0.0,None,1
11,Josquin Des Prés,Ave Maria,188.0,"[24/3.0, 25/1.0, 31/3.0, 35/3.0]","M2, m3, P-8","[188.0, 192.0, 244.0, 276.0]","[(2, 2, 2, 2), (3, 2, 2, 2)]","[4.0, 52.0, 32.0]","[Altus, Altus, Altus, Bassus]",FUGA,4,True,0.0,None,3
12,Josquin Des Prés,Ave Maria,195.0,"[25/2.5, 31/3.0, 32/1.0, 35/3.0, 36/1.0]","m9, m-6, M-3, m-6","[195.0, 244.0, 248.0, 276.0, 280.0]","[(2, 2, 2, -2)]","[49.0, 4.0, 28.0, 4.0]","[Altus, [Superius], Altus, Tenor, Bassus]",FUGA,5,False,0.0,None,2
13,Josquin Des Prés,Ave Maria,196.0,"[25/3.0, 32/3.0, 36/3.0]","M9, P-11, M-3","[196.0, 252.0, 284.0, 284.0]","[(2, 2, -2, -2), (3, 2, -2, -2)]","[56.0, 32.0, 0.0]","[Altus, [Superius], Altus, Bassus]",FUGA,4,True,1.0,Tenor,2
14,Josquin Des Prés,Ave Maria,220.0,"[28/3.0, 28/4.0]",P8,"[220.0, 222.0]","[(-2, -2, -2, 2), (-3, -2, -2, 2)]",[2.0],"[Tenor, [Superius]]",FUGA,2,True,0.0,None,1
15,Josquin Des Prés,Ave Maria,256.0,"[33/1.0, 37/1.0, 40/3.0]","P-8, M13","[256.0, 288.0, 316.0]","[(2, -2, -2, -2), (3, -2, -2, -2)]","[32.0, 28.0]","[Altus, Bassus, [Superius]]",FUGA,3,True,1.0,Tenor,2
16,Josquin Des Prés,Ave Maria,316.0,"[40/3.0, 44/3.0, 44/4.0, 46/2.0, 46/3.0, 46/4....","P5, m-10, m6, M6, M-10, M2","[316.0, 348.0, 350.0, 362.0, 364.0, 366.0, 402.0]","[(3, 2, 2, -3), (2, 2, 2, -3)]","[32.0, 2.0, 12.0, 2.0, 2.0, 36.0]","[Altus, [Superius], Bassus, Tenor, [Superius],...",FUGA,7,True,1.0,Tenor,3
17,Josquin Des Prés,Ave Maria,332.0,"[42/3.0, 50/1.0, 50/2.0, 51/1.0, 51/2.0, 51/3.0]","P5, M6, M-7, M6, M-6","[332.0, 392.0, 394.0, 400.0, 402.0, 404.0]","[(-4, 2, -3, 2), (-2, 2, -3, 2), (-3, 2, -3, 2)]","[60.0, 2.0, 6.0, 2.0, 2.0]","[Bassus, Bassus, Tenor, Bassus, Tenor, Bassus]",FUGA,6,True,0.0,None,2
18,Josquin Des Prés,Ave Maria,340.0,"[43/3.0, 49/4.0]",m-7,"[340.0, 390.0]","[(-2, -3, 2, 2)]",[50.0],"[[Superius], Altus]",FUGA,2,False,1.0,Tenor,1
19,Josquin Des Prés,Ave Maria,344.0,"[44/1.0, 45/4.0, 46/1.0, 47/4.0, 48/1.0, 50/1.0]","M-10, M6, m6, P-5, M6, M-9","[344.0, 344.0, 358.0, 360.0, 374.0, 376.0, 392.0]","[(-2, 2, 2, 2), (-3, 2, 2, 2)]","[0.0, 14.0, 2.0, 14.0, 2.0, 16.0]","[[Superius], Bassus, Tenor, [Superius], Tenor,...",FUGA,7,True,1.0,Bassus,3
20,Josquin Des Prés,Ave Maria,350.0,"[44/4.0, 45/1.0, 46/4.0, 47/1.0]","M6, P-5, M6","[350.0, 352.0, 366.0, 368.0]","[(2, 2, -3, 2)]","[2.0, 14.0, 2.0]","[Tenor, [Superius], Tenor, [Superius]]",ID,4,False,1.0,Bassus,1
21,Josquin Des Prés,Ave Maria,354.0,"[45/2.0, 45/3.0, 47/2.0, 47/3.0]","M6, P-5, m6","[354.0, 356.0, 370.0, 372.0]","[(2, -3, 2, 2)]","[2.0, 14.0, 2.0]","[Tenor, [Superius], Tenor, [Superius]]",ID,4,False,1.0,Bassus,1
22,Josquin Des Prés,Ave Maria,372.0,"[47/3.0, 51/1.0]",P-5,"[372.0, 400.0]","[(-5, 2, 2, 2)]",[28.0],"[Altus, Altus]",FUGA,2,False,0.0,None,1
23,Josquin Des Prés,Ave Maria,376.0,"[48/1.0, 50/2.0]",P-4,"[376.0, 394.0]","[(2, 2, 2, -5)]",[18.0],"[Altus, Altus]",FUGA,2,False,0.0,None,1
24,Josquin Des Prés,Ave Maria,380.0,"[48/3.0, 48/4.0]",P-5,"[380.0, 382.0]","[(2, 2, 2, -2)]",[2.0],"[[Superius], Tenor]",FUGA,2,False,1.0,Bassus,0
25,Josquin Des Prés,Ave Maria,384.0,"[49/1.0, 49/2.0]",P-5,"[384.0, 386.0]","[(2, 2, -2, 2)]",[2.0],"[[Superius], Tenor]",FUGA,2,False,1.0,Bassus,0
26,Josquin Des Prés,Ave Maria,388.0,"[49/3.0, 49/4.0, 50/4.0, 51/1.0]","m6, m-7, m6","[388.0, 390.0, 398.0, 400.0]","[(2, -2, 2, -3)]","[2.0, 8.0, 2.0]","[Bassus, Tenor, Bassus, Tenor]",ID,4,False,0.0,None,2
27,Josquin Des Prés,Ave Maria,392.0,"[50/1.0, 50/2.0, 51/1.0, 51/2.0, 51/3.0]","M6, M-7, M6, M-6","[392.0, 394.0, 400.0, 402.0, 404.0]","[(-2, 2, -3, 2), (-3, 2, -3, 2)]","[2.0, 6.0, 2.0, 2.0]","[Bassus, Tenor, Bassus, Tenor, Bassus]",FUGA,5,True,0.0,None,1
28,Josquin Des Prés,Ave Maria,395.0,"[50/2.5, 50/3.5]",m6,"[395.0, 397.0]","[(2, -3, 2, -2)]",[2.0],"[Bassus, Tenor]",FUGA,2,False,0.0,None,1
29,Josquin Des Prés,Ave Maria,396.0,"[50/3.0, 50/4.0]",M6,"[396.0, 398.0]","[(-3, 2, -2, 2)]",[2.0],"[Bassus, Tenor]",FUGA,2,False,0.0,None,1
30,Josquin Des Prés,Ave Maria,398.0,"[50/4.0, 51/4.0, 53/2.0, 56/3.0, 57/3.0, 61/3....","m-2, M-6, P5, m-7, M-2, m-7, P8, P8, M-7, P1, ...","[398.0, 406.0, 418.0, 444.0, 452.0, 484.0, 492...","[(-2, -2, -2, 2), (-3, -2, -2, 2)]","[8.0, 12.0, 26.0, 8.0, 32.0, 8.0, 55.0, 51.0, ...","[[Superius], [Superius], Altus, [Superius], Al...",FUGA,14,True,0.0,None,11
31,Josquin Des Prés,Ave Maria,401.0,"[51/1.5, 58/2.0, 63/2.0, 69/3.0]","M-9, P-8, P8","[401.0, 458.0, 498.0, 548.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[57.0, 40.0, 50.0]","[[Superius], Altus, Bassus, Altus]",FUGA,4,True,0.0,None,3
32,Josquin Des Prés,Ave Maria,403.0,"[51/2.5, 51/3.5]",m6,"[403.0, 405.0]","[(2, -3, 2, -3)]",[2.0],"[Bassus, Tenor]",FUGA,2,False,0.0,None,1
33,Josquin Des Prés,Ave Maria,405.0,"[51/3.5, 55/4.0, 56/2.0, 60/4.0, 61/2.0]","M9, P-5, P-4, P-5","[405.0, 438.0, 442.0, 478.0, 482.0]","[(2, 2, -3, -2)]","[33.0, 4.0, 36.0, 4.0]","[Altus, [Superius], Altus, Tenor, Bassus]",FUGA,5,False,0.0,None,4
34,Josquin Des Prés,Ave Maria,428.0,"[54/3.0, 55/1.0, 59/3.0, 60/1.0]","P-5, P-4, P-5","[428.0, 432.0, 468.0, 472.0]","[(4, -2, 2, 2)]","[4.0, 36.0, 4.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,0.0,None,3
35,Josquin Des Prés,Ave Maria,432.0,"[55/1.0, 55/3.0, 60/1.0, 60/3.0]","P-5, P-4, P-5","[432.0, 436.0, 472.0, 476.0]","[(-2, 2, 2, -3)]","[4.0, 36.0, 4.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,0.0,None,1
36,Josquin Des Prés,Ave Maria,440.0,"[56/1.0, 56/3.0, 61/1.0, 61/3.0]","P-5, P-4, P-5","[440.0, 444.0, 480.0, 484.0]","[(2, -3, -2, -2)]","[4.0, 36.0, 4.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,0.0,None,3
37,Josquin Des Prés,Ave Maria,448.0,"[57/1.0, 62/1.0, 69/1.0, 74/2.0, 75/3.0, 84/1....","P-8, m7, P1, M2, P1, P4, m-2, M-10, P1, m7, P1...","[448.0, 488.0, 544.0, 586.0, 596.0, 664.0, 672...","[(-3, -2, -2, -2), (-2, -2, -2, -2)]","[40.0, 56.0, 42.0, 10.0, 68.0, 8.0, 4.0, 28.0,...","[Altus, Bassus, Altus, Tenor, Tenor, Altus, [S...",FUGA,28,True,0.0,None,20
38,Josquin Des Prés,Ave Maria,454.0,"[57/4.0, 62/4.0]",P-8,"[454.0, 494.0]","[(-2, 2, -2, 4)]",[40.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,1
39,Josquin Des Prés,Ave Maria,455.0,"[57/4.5, 62/4.5]",P-8,"[455.0, 495.0]","[(2, -2, 4, -2), (3, -2, 4, -2)]",[40.0],"[[Superius], Tenor]",FUGA,2,True,0.0,None,1
40,Josquin Des Prés,Ave Maria,462.0,"[58/4.0, 63/4.0]",P-8,"[462.0, 502.0]","[(-2, 4, -2, 2)]",[40.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,0
41,Josquin Des Prés,Ave Maria,508.0,"[64/3.0, 66/3.0, 67/3.0, 69/3.0, 70/3.0, 73/3.0]","P-5, P-4, P-5, P4, M9","[508.0, 524.0, 532.0, 548.0, 556.0, 580.0]","[(2, -3, 2, -3)]","[16.0, 8.0, 16.0, 8.0, 24.0]","[[Superius], Altus, Tenor, Bassus, Altus, [Sup...",FUGA,6,False,1.0,Bassus,5
42,Josquin Des Prés,Ave Maria,512.0,"[65/1.0, 67/1.0, 68/1.0, 70/1.0, 73/1.0, 74/1.0]","P-5, P-4, P-5, P12, P-12","[512.0, 528.0, 536.0, 552.0, 576.0, 584.0]","[(-2, 2, -3, 2), (-3, 2, -3, 2)]","[16.0, 8.0, 16.0, 24.0, 8.0]","[[Superius], Altus, Tenor, Bassus, [Superius],...",FUGA,6,True,0.0,None,5
43,Josquin Des Prés,Ave Maria,516.0,"[65/3.0, 67/3.0, 68/3.0, 70/3.0, 78/1.0, 81/1.0]","P-5, P-4, P-5, P12, P-8","[516.0, 532.0, 540.0, 556.0, 616.0, 640.0]","[(2, -3, 2, -2)]","[16.0, 8.0, 16.0, 60.0, 24.0]","[[Superius], Altus, Tenor, Bassus, [Superius],...",FUGA,6,False,0.0,None,5
44,Josquin Des Prés,Ave Maria,520.0,"[66/1.0, 68/1.0, 69/1.0, 71/1.0, 73/4.0, 79/1....","P-5, P-4, P-5, P8, P5, P-8, M2","[520.0, 536.0, 544.0, 560.0, 582.0, 624.0, 648...","[(-3, 2, -2, -2), (-2, 2, -2, -2)]","[16.0, 8.0, 16.0, 22.0, 42.0, 24.0, 33.0]","[[Superius], Altus, Tenor, Bassus, Tenor, [Sup...",FUGA,8,True,0.0,None,7
45,Josquin Des Prés,Ave Maria,524.0,"[66/3.0, 68/3.0, 69/3.0, 71/3.0, 74/1.0, 79/3....","P-5, P-4, P-5, P8, P5, P-8, P8, M-6, P1, M2, P1","[524.0, 540.0, 548.0, 564.0, 584.0, 628.0, 652...","[(2, -2, -2, -2), (3, -2, -2, -2)]","[16.0, 8.0, 16.0, 20.0, 44.0, 24.0, 12.0, 44.0...","[[Superius], Altus, Tenor, Bassus, Tenor, [Sup...",FUGA,12,True,0.0,None,8
46,Josquin Des Prés,Ave Maria,558.0,"[70/4.0, 73/1.0]",M-2,"[558.0, 576.0]","[(-3, 2, -3, -2), (-2, 2, -3, -2)]",[18.0],"[Altus, Altus]",FUGA,2,True,0.0,None,1
47,Josquin Des Prés,Ave Maria,566.0,"[71/4.0, 72/1.0]",P-5,"[566.0, 568.0]","[(-3, -2, -2, 5), (-2, -2, -2, 5)]",[2.0],"[Altus, Bassus]",FUGA,2,True,0.0,None,0
48,Josquin Des Prés,Ave Maria,616.0,"[78/1.0, 81/1.0]",P-8,"[616.0, 640.0]","[(5, 2, -2, -2)]",[24.0],"[Altus, Bassus]",FUGA,2,False,0.0,None,1
49,Josquin Des Prés,Ave Maria,624.0,"[79/1.0, 82/1.0, 85/3.0]","P-8, P5","[624.0, 648.0, 676.0]","[(2, -2, -2, 2), (3, -2, -2, 2)]","[24.0, 28.0]","[Altus, Bassus, Altus]",FUGA,3,True,0.0,None,0
50,Josquin Des Prés,Ave Maria,700.0,"[88/3.0, 91/4.5]",M-9,"[700.0, 727.0]","[(-2, 3, -2, -2)]",[27.0],"[Tenor, Bassus]",FUGA,2,False,0.0,None,1
51,Josquin Des Prés,Ave Maria,796.0,"[98/1.0, 98/2.0]",P-5,"[796.0, 800.0]","[(2, 2, -3, 4)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,0
52,Josquin Des Prés,Ave Maria,808.0,"[99/1.0, 99/2.0]",P-5,"[808.0, 812.0]","[(2, -3, 4, -3)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,0
53,Josquin Des Prés,Ave Maria,820.0,"[100/1.0, 100/2.0]",P-5,"[820.0, 824.0]","[(-3, 4, -3, 4)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,0
54,Josquin Des Prés,Ave Maria,832.0,"[101/1.0, 101/2.0]",P-5,"[832.0, 836.0]","[(4, -3, 4, -2)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,0
55,Josquin Des Prés,Ave Maria,844.0,"[102/1.0, 102/2.0]",P-5,"[844.0, 848.0]","[(-2, 4, -2, -2), (-3, 4, -2, -2)]",[4.0],"[[Superius], Tenor]",FUGA,2,True,0.0,None,0
56,Josquin Des Prés,Ave Maria,856.0,"[103/1.0, 103/2.0]",P-5,"[856.0, 860.0]","[(5, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...",[4.0],"[[Superius], Tenor]",FUGA,2,True,0.0,None,0
57,Josquin Des Prés,Ave Maria,874.0,"[104/2.5, 104/3.5]",P-5,"[874.0, 878.0]","[(-2, -2, -2, 4)]",[4.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,1
58,Josquin Des Prés,Ave Maria,876.0,"[104/3.0, 105/1.0]",P-5,"[876.0, 880.0]","[(-3, -2, 4, 2), (-2, -2, 4, 2)]",[4.0],"[[Superius], Tenor]",FUGA,2,True,0.0,None,1
59,Josquin Des Prés,Ave Maria,880.0,"[105/1.0, 107/1.0]",m-2,"[880.0, 904.0]","[(-2, 2, -3, 2), (-3, 2, -3, 2)]",[24.0],"[Bassus, Bassus]",FUGA,2,True,0.0,None,1
60,Josquin Des Prés,Ave Maria,888.0,"[105/3.0, 111/1.0, 114/1.0, 116/2.0, 117/1.0, ...","P5, m-3, M-7, m-2, m10, m-3, M-7, m-2","[888.0, 944.0, 968.0, 986.0, 992.0, 1008.0, 10...","[(2, -2, -2, -2), (3, -2, -2, -2)]","[56.0, 24.0, 18.0, 6.0, 16.0, 24.0, 18.0, 6.0]","[Altus, [Superius], [Superius], Altus, Tenor, ...",FUGA,9,True,1.0,Tenor,8
61,Josquin Des Prés,Ave Maria,892.0,"[106/1.0, 106/2.0]",m6,"[892.0, 896.0]","[(2, -3, 2, -3)]",[4.0],"[Bassus, Tenor]",FUGA,2,False,0.0,None,0
62,Josquin Des Prés,Ave Maria,904.0,"[107/1.0, 107/2.0]",P4,"[904.0, 908.0]","[(-3, 2, -3, -2), (-2, 2, -3, -2)]",[4.0],"[Altus, Tenor]",FUGA,2,True,0.0,None,1
63,Josquin Des Prés,Ave Maria,956.0,"[112/3.0, 120/3.0]",P1,"[956.0, 1020.0]","[(-3, -2, -2, 5), (-2, -2, -2, 5)]",[64.0],"[Altus, Altus]",FUGA,2,True,0.0,None,1
64,Josquin Des Prés,Ave Maria,960.0,"[113/1.0, 116/1.0, 121/1.0, 124/1.0]","P-8, P8, P-8","[960.0, 984.0, 1024.0, 1048.0]","[(-2, -2, -2, 3)]","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,0.0,None,3
65,Josquin Des Prés,Ave Maria,966.0,"[113/4.0, 116/4.0, 121/4.0, 124/4.0]","P-8, P8, P-8","[966.0, 990.0, 1030.0, 1054.0]","[(-2, -2, 3, -2)]","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,0.0,None,3
66,Josquin Des Prés,Ave Maria,967.0,"[113/4.5, 116/4.5, 121/4.5, 124/4.5]","P-8, P8, P-8","[967.0, 991.0, 1031.0, 1055.0]","[(-2, 3, -2, -2)]","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,0.0,None,3
67,Josquin Des Prés,Ave Maria,968.0,"[114/1.0, 117/1.0, 122/1.0, 125/1.0]","P-8, P8, P-8","[968.0, 992.0, 1032.0, 1056.0]","[(5, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,True,0.0,None,3
68,Josquin Des Prés,Ave Maria,972.0,"[114/3.0, 122/3.0]",P1,"[972.0, 1036.0]","[(-2, -2, -3, 5)]",[64.0],"[Bassus, Bassus]",FUGA,2,False,0.0,None,1
69,Josquin Des Prés,Ave Maria,980.0,"[115/3.0, 123/3.0]",P1,"[980.0, 1044.0]","[(-2, -3, 5, -2)]",[64.0],"[Bassus, Bassus]",FUGA,2,False,0.0,None,1
70,Josquin Des Prés,Ave Maria,984.0,"[116/1.0, 124/1.0]",P1,"[984.0, 1048.0]","[(-2, 5, -2, -2), (-3, 5, -2, -2)]",[64.0],"[Bassus, Bassus]",FUGA,2,True,0.0,None,1
71,Josquin Des Prés,Ave Maria,988.0,"[116/3.0, 124/3.0]",P1,"[988.0, 1052.0]","[(4, -2, -2, 2), (3, -2, -2, 2), (5, -2, -2, 2)]",[64.0],"[Bassus, Bassus]",FUGA,2,True,0.0,None,1
72,Josquin Des Prés,Ave Maria,992.0,"[117/1.0, 125/1.0, 130/2.5, 138/3.5, 143/1.0]","P1, m-3, m3, P4","[992.0, 1056.0, 1099.0, 1165.0, 1200.0]","[(-2, -2, 2, 2), (-3, -2, 2, 2)]","[64.0, 43.0, 66.0, 35.0]","[Bassus, Bassus, Bassus, Bassus, Tenor]",FUGA,5,True,0.0,None,4
73,Josquin Des Prés,Ave Maria,998.0,"[117/4.0, 125/4.0]",P1,"[998.0, 1062.0]","[(-2, 2, 2, -2), (-3, 2, 2, -2)]",[64.0],"[Bassus, Bassus]",FUGA,2,True,0.0,None,1
74,Josquin Des Prés,Ave Maria,999.0,"[117/4.5, 125/4.5, 128/1.0, 130/1.0]","P1, P11, P-8","[999.0, 1063.0, 1080.0, 1096.0]","[(2, 2, -2, 2)]","[64.0, 17.0, 16.0]","[Bassus, Bassus, [Superius], Tenor]",FUGA,4,False,0.0,None,2
75,Josquin Des Prés,Ave Maria,1074.0,"[127/2.0, 132/2.0]",P-5,"[1074.0, 1114.0]","[(-2, -2, 2, -3)]",[40.0],"[Altus, Altus]",FUGA,2,False,0.0,None,1
76,Josquin Des Prés,Ave Maria,1080.0,"[128/1.0, 134/3.0, 137/3.0, 139/2.0]","M6, P-8, m-3","[1080.0, 1132.0, 1156.0, 1170.0]","[(-3, 2, -2, -2), (-2, 2, -2, -2)]","[52.0, 24.0, 14.0]","[Altus, [Superius], Tenor, Altus]",FUGA,4,True,1.0,Bassus,3
77,Josquin Des Prés,Ave Maria,1082.0,"[128/2.0, 135/1.0, 138/1.0, 139/3.0]","m7, P-8, P-4","[1082.0, 1136.0, 1160.0, 1172.0]","[(2, -2, -2, 2), (3, -2, -2, 2)]","[54.0, 24.0, 12.0]","[Altus, [Superius], Tenor, Altus]",FUGA,4,True,0.0,None,1
78,Josquin Des Prés,Ave Maria,1084.0,"[128/3.0, 130/3.0]",P-8,"[1084.0, 1100.0]","[(2, -2, 2, 2)]",[16.0],"[[Superius], Tenor]",FUGA,2,False,0.0,None,1
79,Josquin Des Prés,Ave Maria,1088.0,"[129/1.0, 130/3.0, 131/1.0]","m-14, m7","[1088.0, 1100.0, 1104.0]","[(-2, 2, 2, 2), (-3, 2, 2, 2)]","[12.0, 4.0]","[[Superius], Bassus, Tenor]",FUGA,3,True,0.0,None,1
80,Josquin Des Prés,Ave Maria,1096.0,"[130/1.0, 132/1.5, 135/3.5, 137/4.0, 138/2.0, ...","M6, M2, m3, m-7, M-3, M14","[1096.0, 1113.0, 1141.0, 1158.0, 1162.0, 1174....","[(-2, -2, -2, 2), (-3, -2, -2, 2)]","[17.0, 28.0, 17.0, 4.0, 12.0, 62.0]","[Bassus, Altus, Altus, Altus, Bassus, Bassus, ...",FUGA,7,True,0.0,None,6
81,Josquin Des Prés,Ave Maria,1104.0,"[131/1.0, 131/2.5]",M2,"[1104.0, 1107.0]","[(2, 2, 2, 2), (3, 2, 2, 2)]",[3.0],"[Bassus, Bassus]",FUGA,2,True,0.0,None,1
82,Josquin Des Prés,Ave Maria,1124.0,"[133/3.0, 136/3.0, 140/1.5]","P-8, P-8","[1124.0, 1148.0, 1177.0]","[(-2, -2, 2, -2)]","[24.0, 29.0]","[[Superius], Tenor, Bassus]",FUGA,3,False,0.0,None,2
83,Josquin Des Prés,Ave Maria,1136.0,"[135/1.0, 139/3.0]",P-8,"[1136.0, 1172.0]","[(2, -2, -2, -2), (3, -2, -2, -2)]",[36.0],"[Altus, Bassus]",FUGA,2,True,0.0,None,1
84,Josquin Des Prés,Ave Maria,1160.0,"[138/1.0, 143/1.0]",M-3,"[1160.0, 1200.0]","[(5, -2, -2, -2), (4, -2, -2, -2), (3, -2, -2,...",[40.0],"[Bassus, Bassus]",FUGA,2,True,0.0,None,1
85,Josquin Des Prés,Ave Maria,1166.0,"[138/4.0, 139/1.0]",M-3,"[1166.0, 1168.0]","[(2, -3, 2, -2)]",[2.0],"[Altus, Bassus]",FUGA,2,False,0.0,None,0

In [10]:
patterns_with_5 = p_types[p_types["Melodic_Entry_Intervals"].str.contains("m-7, m6")]
patterns_with_5

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps
26,Josquin Des Prés,Ave Maria,388.0,"[49/3.0, 49/4.0, 50/4.0, 51/1.0]","m6, m-7, m6","[388.0, 390.0, 398.0, 400.0]","[(2, -2, 2, -3)]","[2.0, 8.0, 2.0]","[Bassus, Tenor, Bassus, Tenor]",ID,4,False,0.0,None,2

In [11]:
p_types["Melodic_Entry_Intervals"].value_counts().to_frame()

                                                    Melodic_Entry_Intervals
P-5                                                                      13
P-8                                                                       7
P1                                                                        6
P-8, P1                                                                   5
P-8, P8, P-8                                                              4
P-5, P-4, P-5                                                             3
m6                                                                        3
M-3                                                                       3
P-8, P1, P-8                                                              2
M6, P-5, M6                                                               1
P1, m-3, m3, P4                                                           1
P-5, P-4, P-5, P4, M9                                                     1
m-14, m7                                                                  1
M2                                                                        1
m6, m-7, m6                                                               1
P5, M6, M-7, M6, M-6                                                      1
P-8, P5                                                                   1
P-5, P-4, P-5, P12, P-8                                                   1
P5, m-10, m6, M6, M-10, M2                                                1
M6, M-7, M6, M-6                                                          1
M6                                                                        1
M9, P-5, P-4, P-5                                                         1
M9, P-11, M-3                                                             1
P8                                                                        1
m-2, M-6, P5, m-7, M-2, m-7, P8, P8, M-7, P1, m...                        1
P4                                                                        1
M-3, m-2, m2, m-2, M-3, P1, M-2                                           1
m7, P-8, P-4                                                              1
P5, m-3, M-7, m-2, m10, m-3, M-7, m-2                                     1
P-5, P-4, P-5, P12, P-12                                                  1
M-9                                                                       1
P-5, P-4, P-5, P8, P5, P-8, M2                                            1
m9, m-6, M-3, m-6                                                         1
M6, P-5, m6                                                               1
M6, M2, m3, m-7, M-3, M14                                                 1
M2, m3, P-8                                                               1
P-8, m7, P1, M2, P1, P4, m-2, M-10, P1, m7, P1,...                        1
M-2                                                                       1
P-5, P-4, P-5, P8, P5, P-8, P8, M-6, P1, M2, P1                           1
M-9, P-8, P8                                                              1
M6, P-8, m-3                                                              1
P-8, P-8                                                                  1
m-7                                                                       1
P-8, P1, m-9, m9, P-8, M9                                                 1
P-4                                                                       1
P-8, M13                                                                  1
m-2                                                                       1
P1, P11, P-8                                                              1
M-10, M6, m6, P-5, M6, M-9                                                1

## Save to your folder of CSV's here in the Jupyter Hub
* You can save as CSV, or as Excel.
* You will then need to download this to your computer to view it properly
* Note that in the following part of the code below, you will need to give your file a name:


```
saved_csv/**file_name**.xlsx
```

In [13]:
writer = pd.ExcelWriter('saved_csv/file_name.xlsx', engine='xlsxwriter')
p_types.to_excel(writer, sheet_name='Sheet1')
writer.save()

In [14]:
p_types.to_csv('saved_csv/Verdelot_PTypes_MW_7_28_2022.csv')