In [1]:
import crim_intervals
from crim_intervals import * 
from crim_intervals import main_objs
import pandas as pd
import re
import os
import numpy
import itertools
# import collections
MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)

else:
    print(MYDIR, "folder already exists.")
    
MUSDIR = ("Music_Files")
CHECK_FOLDER = os.path.isdir(MUSDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MUSDIR)
    print("created folder : ", MUSDIR)

else:
    print(MUSDIR, "folder already exists.")

saved_csv folder already exists.
Music_Files folder already exists.

## Import Your Piece

- Here you will want to select the appropriate 'prefix' that identifies the location of your file.
- `'Music_Files/'` is for files in the local notebook; `'https://crimproject.org/mei/'` is for the files on CRIM.
- Then provide the full name (and extension) of your music file, such as `'CRIM_Model_0038.mei'`

In [2]:
# Select a prefix:

# prefix = 'Music_Files/'
prefix = 'https://crimproject.org/mei/'

# Add your filename here

mei_file = 'CRIM_Model_0002.mei'

url = prefix + mei_file

piece = importScore(url)

print(piece.metadata)

{'title': 'O gente brunette', 'composer': 'Thomas Champion', 'date': 1548}

In [3]:
df = piece.homorhythm()
df

                     active_voices  number_dur_ngrams  \
Measure Beat Offset
1.0     1.0  0.0               4.0                1.0
        2.0  1.0               4.0                1.0
        3.0  2.0               4.0                1.0
4.0     4.0  15.0              2.0                1.0
10.0    1.0  36.0              3.0                1.0
11.0    1.0  40.0              4.0                1.0
12.0    1.0  44.0              4.0                1.0
        2.0  45.0              4.0                1.0
        3.0  46.0              4.0                1.0
15.0    4.0  59.0              2.0                1.0
22.0    1.0  84.0              4.0                1.0
23.0    1.0  88.0              4.0                1.0
26.0    1.0  100.0             4.0                1.0
        3.0  102.0             4.0                1.0
27.0    1.0  104.0             4.0                1.0
29.0    4.0  115.0             4.0                1.0
30.0    1.0  116.0             4.0                1.0
33.0    3.0  130.0             4.0                1.0
34.0    1.0  132.0             4.0                1.0
35.0    1.0  136.0             4.0                1.0
37.0    3.0  146.0             3.0                1.0
38.0    1.0  148.0             4.0                1.0
        3.0  150.0             4.0                1.0
39.0    1.0  152.0             4.0                1.0
        4.0  155.0             4.0                1.0
40.0    1.0  156.0             4.0                1.0
        3.0  158.0             4.0                1.0
41.0    1.0  160.0             4.0                1.0
45.0    1.0  176.0             4.0                1.0
        3.0  178.0             4.0                1.0
46.0    1.0  180.0             4.0                1.0
47.0    1.0  184.0             4.0                1.0
        2.0  185.0             4.0                1.0
        3.0  186.0             4.0                1.0
56.0    1.0  220.0             3.0                1.0
57.0    1.0  224.0             4.0                1.0
58.0    1.0  228.0             4.0                1.0
        2.0  229.0             4.0                1.0
        3.0  230.0             4.0                1.0
61.0    4.0  243.0             2.0                1.0

                                                  hr_voices  \
Measure Beat Offset
1.0     1.0  0.0     [Superius, Contratenor, Tenor, Bassus]
        2.0  1.0     [Superius, Contratenor, Tenor, Bassus]
        3.0  2.0     [Superius, Contratenor, Tenor, Bassus]
4.0     4.0  15.0                        [Superius, Bassus]
10.0    1.0  36.0              [Contratenor, Tenor, Bassus]
11.0    1.0  40.0    [Superius, Contratenor, Tenor, Bassus]
12.0    1.0  44.0    [Superius, Contratenor, Tenor, Bassus]
        2.0  45.0    [Superius, Contratenor, Tenor, Bassus]
        3.0  46.0    [Superius, Contratenor, Tenor, Bassus]
15.0    4.0  59.0                        [Superius, Bassus]
22.0    1.0  84.0    [Superius, Contratenor, Tenor, Bassus]
23.0    1.0  88.0    [Superius, Contratenor, Tenor, Bassus]
26.0    1.0  100.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  102.0   [Superius, Contratenor, Tenor, Bassus]
27.0    1.0  104.0   [Superius, Contratenor, Tenor, Bassus]
29.0    4.0  115.0   [Superius, Contratenor, Tenor, Bassus]
30.0    1.0  116.0   [Superius, Contratenor, Tenor, Bassus]
33.0    3.0  130.0   [Superius, Contratenor, Tenor, Bassus]
34.0    1.0  132.0   [Superius, Contratenor, Tenor, Bassus]
35.0    1.0  136.0   [Superius, Contratenor, Tenor, Bassus]
37.0    3.0  146.0          [Superius, Contratenor, Bassus]
38.0    1.0  148.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  150.0   [Superius, Contratenor, Tenor, Bassus]
39.0    1.0  152.0   [Superius, Contratenor, Tenor, Bassus]
        4.0  155.0   [Superius, Contratenor, Tenor, Bassus]
40.0    1.0  156.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  158.0   [Superius, Contratenor, Tenor, Bassus]
41.0    1.0  160.0   [Superius, Contratenor, Tenor, Bassus]
45.0    1.0  176.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  178.0   [Superius, Contratenor, Tenor, Bassus]
46.0    1.0  180.0   [Superius, Contratenor, Tenor, Bassus]
47.0    1.0  184.0   [Superius, Contratenor, Tenor, Bassus]
        2.0  185.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  186.0   [Superius, Contratenor, Tenor, Bassus]
56.0    1.0  220.0             [Contratenor, Tenor, Bassus]
57.0    1.0  224.0   [Superius, Contratenor, Tenor, Bassus]
58.0    1.0  228.0   [Superius, Contratenor, Tenor, Bassus]
        2.0  229.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  230.0   [Superius, Contratenor, Tenor, Bassus]
61.0    4.0  243.0                       [Superius, Bassus]

                                    Superius              Contratenor  \
Measure Beat Offset
1.0     1.0  0.0           (O, gen, te, bru)        (O, gen, te, bru)
        2.0  1.0         (gen, te, bru, net)      (gen, te, bru, net)
        3.0  2.0          (te, bru, net, te)       (te, bru, net, te)
4.0     4.0  15.0         (ras, tu, se, ras)                      NaN
10.0    1.0  36.0                        NaN      (et, te, Sou, vent)
11.0    1.0  40.0        (te, Sou, vent, je)      (te, Sou, vent, je)
12.0    1.0  44.0       (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  45.0       (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  46.0         (je, sou, hai, te)       (je, sou, hai, te)
15.0    4.0  59.0         (mon, aise, , mon)                      NaN
22.0    1.0  84.0         (te, Tou, te, nue)       (te, Tou, te, nue)
23.0    1.0  88.0         (Tou, te, nue, en)       (Tou, te, nue, en)
26.0    1.0  100.0   (chet, te, Blanche, et)  (chet, te, Blanche, et)
        3.0  102.0    (te, Blanche, et, net)   (te, Blanche, et, net)
27.0    1.0  104.0    (Blanche, et, net, te)   (Blanche, et, net, te)
29.0    4.0  115.0     (doul, cet, te, Pour)    (doul, cet, te, Pour)
30.0    1.0  116.0      (cet, te, Pour, jou)     (cet, te, Pour, jou)
33.0    3.0  130.0       (da, mours, Si, tu)      (da, mours, Si, tu)
34.0    1.0  132.0       (mours, Si, tu, sa)      (mours, Si, tu, sa)
35.0    1.0  136.0        (Si, tu, sa, vois)       (Si, tu, sa, vois)
37.0    3.0  146.0       (cho, set, te, Qui)      (cho, set, te, Qui)
38.0    1.0  148.0        (set, te, Qui, me)       (set, te, Qui, me)
        3.0  150.0        (te, Qui, me, hai)       (te, Qui, me, hai)
39.0    1.0  152.0        (Qui, me, hai, te)       (Qui, me, hai, te)
        4.0  155.0        (me, hai, te, qui)       (me, hai, te, qui)
40.0    1.0  156.0        (hai, te, qui, me)       (hai, te, qui, me)
        3.0  158.0        (te, qui, me, hai)       (te, qui, me, hai)
41.0    1.0  160.0        (qui, me, hai, te)       (qui, me, hai, te)
45.0    1.0  176.0     (tous, les, jours, O)    (tous, les, jours, O)
        3.0  178.0      (les, jours, O, gen)     (les, jours, O, gen)
46.0    1.0  180.0       (jours, O, gen, te)      (jours, O, gen, te)
47.0    1.0  184.0         (O, gen, te, bru)        (O, gen, te, bru)
        2.0  185.0       (gen, te, bru, net)      (gen, te, bru, net)
        3.0  186.0        (te, bru, net, te)       (te, bru, net, te)
56.0    1.0  220.0                       NaN      (et, te, Sou, vent)
57.0    1.0  224.0       (te, Sou, vent, je)      (te, Sou, vent, je)
58.0    1.0  228.0      (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  229.0      (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  230.0        (je, sou, hai, te)       (je, sou, hai, te)
61.0    4.0  243.0        (mon, aise, , mon)                      NaN

                                       Tenor                   Bassus  \
Measure Beat Offset
1.0     1.0  0.0           (O, gen, te, bru)        (O, gen, te, bru)
        2.0  1.0         (gen, te, bru, net)      (gen, te, bru, net)
        3.0  2.0          (te, bru, net, te)       (te, bru, net, te)
4.0     4.0  15.0                        NaN       (ras, tu, se, ras)
10.0    1.0  36.0        (et, te, Sou, vent)      (et, te, Sou, vent)
11.0    1.0  40.0        (te, Sou, vent, je)      (te, Sou, vent, je)
12.0    1.0  44.0       (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  45.0       (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  46.0         (je, sou, hai, te)       (je, sou, hai, te)
15.0    4.0  59.0                        NaN       (mon, aise, , mon)
22.0    1.0  84.0         (te, Tou, te, nue)       (te, Tou, te, nue)
23.0    1.0  88.0         (Tou, te, nue, en)       (Tou, te, nue, en)
26.0    1.0  100.0   (chet, te, Blanche, et)  (chet, te, Blanche, et)
        3.0  102.0    (te, Blanche, et, net)   (te, Blanche, et, net)
27.0    1.0  104.0    (Blanche, et, net, te)   (Blanche, et, net, te)
29.0    4.0  115.0     (doul, cet, te, Pour)    (doul, cet, te, Pour)
30.0    1.0  116.0      (cet, te, Pour, jou)     (cet, te, Pour, jou)
33.0    3.0  130.0       (da, mours, Si, tu)      (da, mours, Si, tu)
34.0    1.0  132.0       (mours, Si, tu, sa)      (mours, Si, tu, sa)
35.0    1.0  136.0        (Si, tu, sa, vois)       (Si, tu, sa, vois)
37.0    3.0  146.0                       NaN      (cho, set, te, Qui)
38.0    1.0  148.0        (set, te, Qui, me)       (set, te, Qui, me)
        3.0  150.0        (te, Qui, me, hai)       (te, Qui, me, hai)
39.0    1.0  152.0        (Qui, me, hai, te)       (Qui, me, hai, te)
        4.0  155.0        (me, hai, te, qui)       (me, hai, te, qui)
40.0    1.0  156.0        (hai, te, qui, me)       (hai, te, qui, me)
        3.0  158.0        (te, qui, me, hai)       (te, qui, me, hai)
41.0    1.0  160.0        (qui, me, hai, te)       (qui, me, hai, te)
45.0    1.0  176.0     (tous, les, jours, O)    (tous, les, jours, O)
        3.0  178.0      (les, jours, O, gen)     (les, jours, O, gen)
46.0    1.0  180.0       (jours, O, gen, te)      (jours, O, gen, te)
47.0    1.0  184.0         (O, gen, te, bru)        (O, gen, te, bru)
        2.0  185.0       (gen, te, bru, net)      (gen, te, bru, net)
        3.0  186.0        (te, bru, net, te)       (te, bru, net, te)
56.0    1.0  220.0       (et, te, Sou, vent)      (et, te, Sou, vent)
57.0    1.0  224.0       (te, Sou, vent, je)      (te, Sou, vent, je)
58.0    1.0  228.0      (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  229.0      (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  230.0        (je, sou, hai, te)       (je, sou, hai, te)
61.0    4.0  243.0                       NaN       (mon, aise, , mon)

                                                          syllable_set  \
Measure Beat Offset
1.0     1.0  0.0     [(O, gen, te, bru), (O, gen, te, bru), (O, gen...
        2.0  1.0     [(gen, te, bru, net), (gen, te, bru, net), (ge...
        3.0  2.0     [(te, bru, net, te), (te, bru, net, te), (te, ...
4.0     4.0  15.0             [(ras, tu, se, ras), (ras, tu, se, ras)]
10.0    1.0  36.0    [(et, te, Sou, vent), (et, te, Sou, vent), (et...
11.0    1.0  40.0    [(te, Sou, vent, je), (te, Sou, vent, je), (te...
12.0    1.0  44.0    [(Sou, vent, je, sou), (Sou, vent, je, sou), (...
        2.0  45.0    [(vent, je, sou, hai), (vent, je, sou, hai), (...
        3.0  46.0    [(je, sou, hai, te), (je, sou, hai, te), (je, ...
15.0    4.0  59.0             [(mon, aise, , mon), (mon, aise, , mon)]
22.0    1.0  84.0    [(te, Tou, te, nue), (te, Tou, te, nue), (te, ...
23.0    1.0  88.0    [(Tou, te, nue, en), (Tou, te, nue, en), (Tou,...
26.0    1.0  100.0   [(chet, te, Blanche, et), (chet, te, Blanche, ...
        3.0  102.0   [(te, Blanche, et, net), (te, Blanche, et, net...
27.0    1.0  104.0   [(Blanche, et, net, te), (Blanche, et, net, te...
29.0    4.0  115.0   [(doul, cet, te, Pour), (doul, cet, te, Pour),...
30.0    1.0  116.0   [(cet, te, Pour, jou), (cet, te, Pour, jou), (...
33.0    3.0  130.0   [(da, mours, Si, tu), (da, mours, Si, tu), (da...
34.0    1.0  132.0   [(mours, Si, tu, sa), (mours, Si, tu, sa), (mo...
35.0    1.0  136.0   [(Si, tu, sa, vois), (Si, tu, sa, vois), (Si, ...
37.0    3.0  146.0   [(cho, set, te, Qui), (cho, set, te, Qui), (ch...
38.0    1.0  148.0   [(set, te, Qui, me), (set, te, Qui, me), (set,...
        3.0  150.0   [(te, Qui, me, hai), (te, Qui, me, hai), (te, ...
39.0    1.0  152.0   [(Qui, me, hai, te), (Qui, me, hai, te), (Qui,...
        4.0  155.0   [(me, hai, te, qui), (me, hai, te, qui), (me, ...
40.0    1.0  156.0   [(hai, te, qui, me), (hai, te, qui, me), (hai,...
        3.0  158.0   [(te, qui, me, hai), (te, qui, me, hai), (te, ...
41.0    1.0  160.0   [(qui, me, hai, te), (qui, me, hai, te), (qui,...
45.0    1.0  176.0   [(tous, les, jours, O), (tous, les, jours, O),...
        3.0  178.0   [(les, jours, O, gen), (les, jours, O, gen), (...
46.0    1.0  180.0   [(jours, O, gen, te), (jours, O, gen, te), (jo...
47.0    1.0  184.0   [(O, gen, te, bru), (O, gen, te, bru), (O, gen...
        2.0  185.0   [(gen, te, bru, net), (gen, te, bru, net), (ge...
        3.0  186.0   [(te, bru, net, te), (te, bru, net, te), (te, ...
56.0    1.0  220.0   [(et, te, Sou, vent), (et, te, Sou, vent), (et...
57.0    1.0  224.0   [(te, Sou, vent, je), (te, Sou, vent, je), (te...
58.0    1.0  228.0   [(Sou, vent, je, sou), (Sou, vent, je, sou), (...
        2.0  229.0   [(vent, je, sou, hai), (vent, je, sou, hai), (...
        3.0  230.0   [(je, sou, hai, te), (je, sou, hai, te), (je, ...
61.0    4.0  243.0            [(mon, aise, , mon), (mon, aise, , mon)]

                     count_lyr_ngrams  active_syll_voices voice_match  \
Measure Beat Offset
1.0     1.0  0.0                  1.0                 4.0        True
        2.0  1.0                  1.0                 4.0        True
        3.0  2.0                  1.0                 4.0        True
4.0     4.0  15.0                 1.0                 2.0        True
10.0    1.0  36.0                 1.0                 3.0        True
11.0    1.0  40.0                 1.0                 4.0        True
12.0    1.0  44.0                 1.0                 4.0        True
        2.0  45.0                 1.0                 4.0        True
        3.0  46.0                 1.0                 4.0        True
15.0    4.0  59.0                 1.0                 2.0        True
22.0    1.0  84.0                 1.0                 4.0        True
23.0    1.0  88.0                 1.0                 4.0        True
26.0    1.0  100.0                1.0                 4.0        True
        3.0  102.0                1.0                 4.0        True
27.0    1.0  104.0                1.0                 4.0        True
29.0    4.0  115.0                1.0                 4.0        True
30.0    1.0  116.0                1.0                 4.0        True
33.0    3.0  130.0                1.0                 4.0        True
34.0    1.0  132.0                1.0                 4.0        True
35.0    1.0  136.0                1.0                 4.0        True
37.0    3.0  146.0                1.0                 3.0        True
38.0    1.0  148.0                1.0                 4.0        True
        3.0  150.0                1.0                 4.0        True
39.0    1.0  152.0                1.0                 4.0        True
        4.0  155.0                1.0                 4.0        True
40.0    1.0  156.0                1.0                 4.0        True
        3.0  158.0                1.0                 4.0        True
41.0    1.0  160.0                1.0                 4.0        True
45.0    1.0  176.0                1.0                 4.0        True
        3.0  178.0                1.0                 4.0        True
46.0    1.0  180.0                1.0                 4.0        True
47.0    1.0  184.0                1.0                 4.0        True
        2.0  185.0                1.0                 4.0        True
        3.0  186.0                1.0                 4.0        True
56.0    1.0  220.0                1.0                 3.0        True
57.0    1.0  224.0                1.0                 4.0        True
58.0    1.0  228.0                1.0                 4.0        True
        2.0  229.0                1.0                 4.0        True
        3.0  230.0                1.0                 4.0        True
61.0    4.0  243.0                1.0                 2.0        True

                     ngram_length  Progress
Measure Beat Offset
1.0     1.0  0.0              4.0  0.000000
        2.0  1.0              4.0  0.003521
        3.0  2.0              4.0  0.007042
4.0     4.0  15.0             4.0  0.052817
10.0    1.0  36.0             4.0  0.126761
11.0    1.0  40.0             4.0  0.140845
12.0    1.0  44.0             4.0  0.154930
        2.0  45.0             4.0  0.158451
        3.0  46.0             4.0  0.161972
15.0    4.0  59.0             4.0  0.207746
22.0    1.0  84.0             4.0  0.295775
23.0    1.0  88.0             4.0  0.309859
26.0    1.0  100.0            4.0  0.352113
        3.0  102.0            4.0  0.359155
27.0    1.0  104.0            4.0  0.366197
29.0    4.0  115.0            4.0  0.404930
30.0    1.0  116.0            4.0  0.408451
33.0    3.0  130.0            4.0  0.457746
34.0    1.0  132.0            4.0  0.464789
35.0    1.0  136.0            4.0  0.478873
37.0    3.0  146.0            4.0  0.514085
38.0    1.0  148.0            4.0  0.521127
        3.0  150.0            4.0  0.528169
39.0    1.0  152.0            4.0  0.535211
        4.0  155.0            4.0  0.545775
40.0    1.0  156.0            4.0  0.549296
        3.0  158.0            4.0  0.556338
41.0    1.0  160.0            4.0  0.563380
45.0    1.0  176.0            4.0  0.619718
        3.0  178.0            4.0  0.626761
46.0    1.0  180.0            4.0  0.633803
47.0    1.0  184.0            4.0  0.647887
        2.0  185.0            4.0  0.651408
        3.0  186.0            4.0  0.654930
56.0    1.0  220.0            4.0  0.774648
57.0    1.0  224.0            4.0  0.788732
58.0    1.0  228.0            4.0  0.802817
        2.0  229.0            4.0  0.806338
        3.0  230.0            4.0  0.809859
61.0    4.0  243.0            4.0  0.855634

In [4]:
# hr


ngram_length = 4
full_hr = True
 # active version with lyric ngs
nr = piece.notes()
dur = piece.durations(df=nr)

# add ng = exclude=[] to arguments in ngrams
# specify ngram length with arguments
ng = piece.ngrams(df=dur, n=ngram_length, exclude=[])
dur_ngrams = []
for index, rows in ng.iterrows():
    dur_ngrams_no_nan = [x for x in rows if pd.isnull(x) == False]
    dur_ngrams.append(dur_ngrams_no_nan)
ng['dur_ngrams'] = dur_ngrams
ng['active_voices'] = ng['dur_ngrams'].apply(len)
ng['number_dur_ngrams'] = ng['dur_ngrams'].apply(set).apply(len)

# from JS to check full_hr or partial
if full_hr == True:
    ng = ng[(ng['number_dur_ngrams'] < 2) & (ng['active_voices'] > 1)]
else:
    ng = ng[ng['number_dur_ngrams'] < ng['active_voices']]

#find involved voices

hr_voices = []
for index, rows in ng. iterrows():
    seen = set()
    hr_ngrams = []
    for x in rows['dur_ngrams']:
        if x in seen and not x in hr_ngrams:
            hr_ngrams.append(x)
        else:
            seen.add(x)
    hr_v = []
    for index, value in rows.items():
        if value in hr_ngrams:
            hr_v.append(index)
    hr_voices.append(hr_v)

ng['hr_voices'] = hr_voices

# get the lyrics as ngrams to match the durations
lyrics = piece.lyrics()
lyrics = lyrics.applymap(piece._alpha_only)

# specify ngram length with arguments
lyrics_ng = piece.ngrams(df=lyrics, n=ngram_length)

# filter lyric ng's according to what we already know about durations:
ng_list = ng.index.to_list()
filtered_lyric_ngs = lyrics_ng.filter(items = ng_list, axis=0)

# count the lyric_ngrams at each position
syll_set = []
for index, rows in filtered_lyric_ngs.iterrows():
    syll_no_nan = [z for z in rows if pd.isnull(z) == False]
    syll_set.append(syll_no_nan)
filtered_lyric_ngs['syllable_set'] = syll_set
filtered_lyric_ngs["count_lyr_ngrams"] = filtered_lyric_ngs["syllable_set"].apply(set).apply(len)

# and the number of active voices
filtered_lyric_ngs['active_syll_voices'] = filtered_lyric_ngs['syllable_set'].apply(len)
if full_hr == True:
    hr_sylls_mask = filtered_lyric_ngs[(filtered_lyric_ngs['active_syll_voices'] > 1) & (filtered_lyric_ngs['count_lyr_ngrams'] < 2)]
else:
    hr_sylls_mask = filtered_lyric_ngs[filtered_lyric_ngs['active_syll_voices'] > filtered_lyric_ngs['count_lyr_ngrams']]

# combine of both dur_ng and lyric_ng to show passages where more than 2 voices have the same syllables and durations
ng = ng[['active_voices', 'number_dur_ngrams', 'hr_voices']]
hr = pd.merge(ng, hr_sylls_mask, left_index=True, right_index=True)
# the intersection of coordinated durations and coordinate lyrics
hr['voice_match'] = hr['active_voices'] == hr['active_syll_voices']
# retain ngram length for use with ema
hr['ngram_length'] = int(ngram_length)
result = piece.detailIndex(hr, offset=True)
# result["Progress"] = (result.index.get_level_values(2) / piece.notes().index[-1])

# if len(result) == 0:
#     print ("No HR passages found in " + piece.metadata['composer'] + ":" + piece.metadata['title'])
# else:
#     result
result

/var/folders/_s/4t2p1z2x0yxcv068dtqj31tw0000gq/T/ipykernel_46100/41547554.py:48: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  lyrics = lyrics.applymap(piece._alpha_only)

                     active_voices  number_dur_ngrams  \
Measure Beat Offset
1.0     1.0  0.0               4.0                1.0
        2.0  1.0               4.0                1.0
        3.0  2.0               4.0                1.0
4.0     4.0  15.0              2.0                1.0
10.0    1.0  36.0              3.0                1.0
11.0    1.0  40.0              4.0                1.0
12.0    1.0  44.0              4.0                1.0
        2.0  45.0              4.0                1.0
        3.0  46.0              4.0                1.0
15.0    4.0  59.0              2.0                1.0
22.0    1.0  84.0              4.0                1.0
23.0    1.0  88.0              4.0                1.0
26.0    1.0  100.0             4.0                1.0
        3.0  102.0             4.0                1.0
27.0    1.0  104.0             4.0                1.0
29.0    4.0  115.0             4.0                1.0
30.0    1.0  116.0             4.0                1.0
33.0    3.0  130.0             4.0                1.0
34.0    1.0  132.0             4.0                1.0
35.0    1.0  136.0             4.0                1.0
37.0    3.0  146.0             3.0                1.0
38.0    1.0  148.0             4.0                1.0
        3.0  150.0             4.0                1.0
39.0    1.0  152.0             4.0                1.0
        4.0  155.0             4.0                1.0
40.0    1.0  156.0             4.0                1.0
        3.0  158.0             4.0                1.0
41.0    1.0  160.0             4.0                1.0
45.0    1.0  176.0             4.0                1.0
        3.0  178.0             4.0                1.0
46.0    1.0  180.0             4.0                1.0
47.0    1.0  184.0             4.0                1.0
        2.0  185.0             4.0                1.0
        3.0  186.0             4.0                1.0
56.0    1.0  220.0             3.0                1.0
57.0    1.0  224.0             4.0                1.0
58.0    1.0  228.0             4.0                1.0
        2.0  229.0             4.0                1.0
        3.0  230.0             4.0                1.0
61.0    4.0  243.0             2.0                1.0

                                                  hr_voices  \
Measure Beat Offset
1.0     1.0  0.0     [Superius, Contratenor, Tenor, Bassus]
        2.0  1.0     [Superius, Contratenor, Tenor, Bassus]
        3.0  2.0     [Superius, Contratenor, Tenor, Bassus]
4.0     4.0  15.0                        [Superius, Bassus]
10.0    1.0  36.0              [Contratenor, Tenor, Bassus]
11.0    1.0  40.0    [Superius, Contratenor, Tenor, Bassus]
12.0    1.0  44.0    [Superius, Contratenor, Tenor, Bassus]
        2.0  45.0    [Superius, Contratenor, Tenor, Bassus]
        3.0  46.0    [Superius, Contratenor, Tenor, Bassus]
15.0    4.0  59.0                        [Superius, Bassus]
22.0    1.0  84.0    [Superius, Contratenor, Tenor, Bassus]
23.0    1.0  88.0    [Superius, Contratenor, Tenor, Bassus]
26.0    1.0  100.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  102.0   [Superius, Contratenor, Tenor, Bassus]
27.0    1.0  104.0   [Superius, Contratenor, Tenor, Bassus]
29.0    4.0  115.0   [Superius, Contratenor, Tenor, Bassus]
30.0    1.0  116.0   [Superius, Contratenor, Tenor, Bassus]
33.0    3.0  130.0   [Superius, Contratenor, Tenor, Bassus]
34.0    1.0  132.0   [Superius, Contratenor, Tenor, Bassus]
35.0    1.0  136.0   [Superius, Contratenor, Tenor, Bassus]
37.0    3.0  146.0          [Superius, Contratenor, Bassus]
38.0    1.0  148.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  150.0   [Superius, Contratenor, Tenor, Bassus]
39.0    1.0  152.0   [Superius, Contratenor, Tenor, Bassus]
        4.0  155.0   [Superius, Contratenor, Tenor, Bassus]
40.0    1.0  156.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  158.0   [Superius, Contratenor, Tenor, Bassus]
41.0    1.0  160.0   [Superius, Contratenor, Tenor, Bassus]
45.0    1.0  176.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  178.0   [Superius, Contratenor, Tenor, Bassus]
46.0    1.0  180.0   [Superius, Contratenor, Tenor, Bassus]
47.0    1.0  184.0   [Superius, Contratenor, Tenor, Bassus]
        2.0  185.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  186.0   [Superius, Contratenor, Tenor, Bassus]
56.0    1.0  220.0             [Contratenor, Tenor, Bassus]
57.0    1.0  224.0   [Superius, Contratenor, Tenor, Bassus]
58.0    1.0  228.0   [Superius, Contratenor, Tenor, Bassus]
        2.0  229.0   [Superius, Contratenor, Tenor, Bassus]
        3.0  230.0   [Superius, Contratenor, Tenor, Bassus]
61.0    4.0  243.0                       [Superius, Bassus]

                                    Superius              Contratenor  \
Measure Beat Offset
1.0     1.0  0.0           (O, gen, te, bru)        (O, gen, te, bru)
        2.0  1.0         (gen, te, bru, net)      (gen, te, bru, net)
        3.0  2.0          (te, bru, net, te)       (te, bru, net, te)
4.0     4.0  15.0         (ras, tu, se, ras)                      NaN
10.0    1.0  36.0                        NaN      (et, te, Sou, vent)
11.0    1.0  40.0        (te, Sou, vent, je)      (te, Sou, vent, je)
12.0    1.0  44.0       (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  45.0       (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  46.0         (je, sou, hai, te)       (je, sou, hai, te)
15.0    4.0  59.0         (mon, aise, , mon)                      NaN
22.0    1.0  84.0         (te, Tou, te, nue)       (te, Tou, te, nue)
23.0    1.0  88.0         (Tou, te, nue, en)       (Tou, te, nue, en)
26.0    1.0  100.0   (chet, te, Blanche, et)  (chet, te, Blanche, et)
        3.0  102.0    (te, Blanche, et, net)   (te, Blanche, et, net)
27.0    1.0  104.0    (Blanche, et, net, te)   (Blanche, et, net, te)
29.0    4.0  115.0     (doul, cet, te, Pour)    (doul, cet, te, Pour)
30.0    1.0  116.0      (cet, te, Pour, jou)     (cet, te, Pour, jou)
33.0    3.0  130.0       (da, mours, Si, tu)      (da, mours, Si, tu)
34.0    1.0  132.0       (mours, Si, tu, sa)      (mours, Si, tu, sa)
35.0    1.0  136.0        (Si, tu, sa, vois)       (Si, tu, sa, vois)
37.0    3.0  146.0       (cho, set, te, Qui)      (cho, set, te, Qui)
38.0    1.0  148.0        (set, te, Qui, me)       (set, te, Qui, me)
        3.0  150.0        (te, Qui, me, hai)       (te, Qui, me, hai)
39.0    1.0  152.0        (Qui, me, hai, te)       (Qui, me, hai, te)
        4.0  155.0        (me, hai, te, qui)       (me, hai, te, qui)
40.0    1.0  156.0        (hai, te, qui, me)       (hai, te, qui, me)
        3.0  158.0        (te, qui, me, hai)       (te, qui, me, hai)
41.0    1.0  160.0        (qui, me, hai, te)       (qui, me, hai, te)
45.0    1.0  176.0     (tous, les, jours, O)    (tous, les, jours, O)
        3.0  178.0      (les, jours, O, gen)     (les, jours, O, gen)
46.0    1.0  180.0       (jours, O, gen, te)      (jours, O, gen, te)
47.0    1.0  184.0         (O, gen, te, bru)        (O, gen, te, bru)
        2.0  185.0       (gen, te, bru, net)      (gen, te, bru, net)
        3.0  186.0        (te, bru, net, te)       (te, bru, net, te)
56.0    1.0  220.0                       NaN      (et, te, Sou, vent)
57.0    1.0  224.0       (te, Sou, vent, je)      (te, Sou, vent, je)
58.0    1.0  228.0      (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  229.0      (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  230.0        (je, sou, hai, te)       (je, sou, hai, te)
61.0    4.0  243.0        (mon, aise, , mon)                      NaN

                                       Tenor                   Bassus  \
Measure Beat Offset
1.0     1.0  0.0           (O, gen, te, bru)        (O, gen, te, bru)
        2.0  1.0         (gen, te, bru, net)      (gen, te, bru, net)
        3.0  2.0          (te, bru, net, te)       (te, bru, net, te)
4.0     4.0  15.0                        NaN       (ras, tu, se, ras)
10.0    1.0  36.0        (et, te, Sou, vent)      (et, te, Sou, vent)
11.0    1.0  40.0        (te, Sou, vent, je)      (te, Sou, vent, je)
12.0    1.0  44.0       (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  45.0       (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  46.0         (je, sou, hai, te)       (je, sou, hai, te)
15.0    4.0  59.0                        NaN       (mon, aise, , mon)
22.0    1.0  84.0         (te, Tou, te, nue)       (te, Tou, te, nue)
23.0    1.0  88.0         (Tou, te, nue, en)       (Tou, te, nue, en)
26.0    1.0  100.0   (chet, te, Blanche, et)  (chet, te, Blanche, et)
        3.0  102.0    (te, Blanche, et, net)   (te, Blanche, et, net)
27.0    1.0  104.0    (Blanche, et, net, te)   (Blanche, et, net, te)
29.0    4.0  115.0     (doul, cet, te, Pour)    (doul, cet, te, Pour)
30.0    1.0  116.0      (cet, te, Pour, jou)     (cet, te, Pour, jou)
33.0    3.0  130.0       (da, mours, Si, tu)      (da, mours, Si, tu)
34.0    1.0  132.0       (mours, Si, tu, sa)      (mours, Si, tu, sa)
35.0    1.0  136.0        (Si, tu, sa, vois)       (Si, tu, sa, vois)
37.0    3.0  146.0                       NaN      (cho, set, te, Qui)
38.0    1.0  148.0        (set, te, Qui, me)       (set, te, Qui, me)
        3.0  150.0        (te, Qui, me, hai)       (te, Qui, me, hai)
39.0    1.0  152.0        (Qui, me, hai, te)       (Qui, me, hai, te)
        4.0  155.0        (me, hai, te, qui)       (me, hai, te, qui)
40.0    1.0  156.0        (hai, te, qui, me)       (hai, te, qui, me)
        3.0  158.0        (te, qui, me, hai)       (te, qui, me, hai)
41.0    1.0  160.0        (qui, me, hai, te)       (qui, me, hai, te)
45.0    1.0  176.0     (tous, les, jours, O)    (tous, les, jours, O)
        3.0  178.0      (les, jours, O, gen)     (les, jours, O, gen)
46.0    1.0  180.0       (jours, O, gen, te)      (jours, O, gen, te)
47.0    1.0  184.0         (O, gen, te, bru)        (O, gen, te, bru)
        2.0  185.0       (gen, te, bru, net)      (gen, te, bru, net)
        3.0  186.0        (te, bru, net, te)       (te, bru, net, te)
56.0    1.0  220.0       (et, te, Sou, vent)      (et, te, Sou, vent)
57.0    1.0  224.0       (te, Sou, vent, je)      (te, Sou, vent, je)
58.0    1.0  228.0      (Sou, vent, je, sou)     (Sou, vent, je, sou)
        2.0  229.0      (vent, je, sou, hai)     (vent, je, sou, hai)
        3.0  230.0        (je, sou, hai, te)       (je, sou, hai, te)
61.0    4.0  243.0                       NaN       (mon, aise, , mon)

                                                          syllable_set  \
Measure Beat Offset
1.0     1.0  0.0     [(O, gen, te, bru), (O, gen, te, bru), (O, gen...
        2.0  1.0     [(gen, te, bru, net), (gen, te, bru, net), (ge...
        3.0  2.0     [(te, bru, net, te), (te, bru, net, te), (te, ...
4.0     4.0  15.0             [(ras, tu, se, ras), (ras, tu, se, ras)]
10.0    1.0  36.0    [(et, te, Sou, vent), (et, te, Sou, vent), (et...
11.0    1.0  40.0    [(te, Sou, vent, je), (te, Sou, vent, je), (te...
12.0    1.0  44.0    [(Sou, vent, je, sou), (Sou, vent, je, sou), (...
        2.0  45.0    [(vent, je, sou, hai), (vent, je, sou, hai), (...
        3.0  46.0    [(je, sou, hai, te), (je, sou, hai, te), (je, ...
15.0    4.0  59.0             [(mon, aise, , mon), (mon, aise, , mon)]
22.0    1.0  84.0    [(te, Tou, te, nue), (te, Tou, te, nue), (te, ...
23.0    1.0  88.0    [(Tou, te, nue, en), (Tou, te, nue, en), (Tou,...
26.0    1.0  100.0   [(chet, te, Blanche, et), (chet, te, Blanche, ...
        3.0  102.0   [(te, Blanche, et, net), (te, Blanche, et, net...
27.0    1.0  104.0   [(Blanche, et, net, te), (Blanche, et, net, te...
29.0    4.0  115.0   [(doul, cet, te, Pour), (doul, cet, te, Pour),...
30.0    1.0  116.0   [(cet, te, Pour, jou), (cet, te, Pour, jou), (...
33.0    3.0  130.0   [(da, mours, Si, tu), (da, mours, Si, tu), (da...
34.0    1.0  132.0   [(mours, Si, tu, sa), (mours, Si, tu, sa), (mo...
35.0    1.0  136.0   [(Si, tu, sa, vois), (Si, tu, sa, vois), (Si, ...
37.0    3.0  146.0   [(cho, set, te, Qui), (cho, set, te, Qui), (ch...
38.0    1.0  148.0   [(set, te, Qui, me), (set, te, Qui, me), (set,...
        3.0  150.0   [(te, Qui, me, hai), (te, Qui, me, hai), (te, ...
39.0    1.0  152.0   [(Qui, me, hai, te), (Qui, me, hai, te), (Qui,...
        4.0  155.0   [(me, hai, te, qui), (me, hai, te, qui), (me, ...
40.0    1.0  156.0   [(hai, te, qui, me), (hai, te, qui, me), (hai,...
        3.0  158.0   [(te, qui, me, hai), (te, qui, me, hai), (te, ...
41.0    1.0  160.0   [(qui, me, hai, te), (qui, me, hai, te), (qui,...
45.0    1.0  176.0   [(tous, les, jours, O), (tous, les, jours, O),...
        3.0  178.0   [(les, jours, O, gen), (les, jours, O, gen), (...
46.0    1.0  180.0   [(jours, O, gen, te), (jours, O, gen, te), (jo...
47.0    1.0  184.0   [(O, gen, te, bru), (O, gen, te, bru), (O, gen...
        2.0  185.0   [(gen, te, bru, net), (gen, te, bru, net), (ge...
        3.0  186.0   [(te, bru, net, te), (te, bru, net, te), (te, ...
56.0    1.0  220.0   [(et, te, Sou, vent), (et, te, Sou, vent), (et...
57.0    1.0  224.0   [(te, Sou, vent, je), (te, Sou, vent, je), (te...
58.0    1.0  228.0   [(Sou, vent, je, sou), (Sou, vent, je, sou), (...
        2.0  229.0   [(vent, je, sou, hai), (vent, je, sou, hai), (...
        3.0  230.0   [(je, sou, hai, te), (je, sou, hai, te), (je, ...
61.0    4.0  243.0            [(mon, aise, , mon), (mon, aise, , mon)]

                     count_lyr_ngrams  active_syll_voices voice_match  \
Measure Beat Offset
1.0     1.0  0.0                  1.0                 4.0        True
        2.0  1.0                  1.0                 4.0        True
        3.0  2.0                  1.0                 4.0        True
4.0     4.0  15.0                 1.0                 2.0        True
10.0    1.0  36.0                 1.0                 3.0        True
11.0    1.0  40.0                 1.0                 4.0        True
12.0    1.0  44.0                 1.0                 4.0        True
        2.0  45.0                 1.0                 4.0        True
        3.0  46.0                 1.0                 4.0        True
15.0    4.0  59.0                 1.0                 2.0        True
22.0    1.0  84.0                 1.0                 4.0        True
23.0    1.0  88.0                 1.0                 4.0        True
26.0    1.0  100.0                1.0                 4.0        True
        3.0  102.0                1.0                 4.0        True
27.0    1.0  104.0                1.0                 4.0        True
29.0    4.0  115.0                1.0                 4.0        True
30.0    1.0  116.0                1.0                 4.0        True
33.0    3.0  130.0                1.0                 4.0        True
34.0    1.0  132.0                1.0                 4.0        True
35.0    1.0  136.0                1.0                 4.0        True
37.0    3.0  146.0                1.0                 3.0        True
38.0    1.0  148.0                1.0                 4.0        True
        3.0  150.0                1.0                 4.0        True
39.0    1.0  152.0                1.0                 4.0        True
        4.0  155.0                1.0                 4.0        True
40.0    1.0  156.0                1.0                 4.0        True
        3.0  158.0                1.0                 4.0        True
41.0    1.0  160.0                1.0                 4.0        True
45.0    1.0  176.0                1.0                 4.0        True
        3.0  178.0                1.0                 4.0        True
46.0    1.0  180.0                1.0                 4.0        True
47.0    1.0  184.0                1.0                 4.0        True
        2.0  185.0                1.0                 4.0        True
        3.0  186.0                1.0                 4.0        True
56.0    1.0  220.0                1.0                 3.0        True
57.0    1.0  224.0                1.0                 4.0        True
58.0    1.0  228.0                1.0                 4.0        True
        2.0  229.0                1.0                 4.0        True
        3.0  230.0                1.0                 4.0        True
61.0    4.0  243.0                1.0                 2.0        True

                     ngram_length
Measure Beat Offset
1.0     1.0  0.0              4.0
        2.0  1.0              4.0
        3.0  2.0              4.0
4.0     4.0  15.0             4.0
10.0    1.0  36.0             4.0
11.0    1.0  40.0             4.0
12.0    1.0  44.0             4.0
        2.0  45.0             4.0
        3.0  46.0             4.0
15.0    4.0  59.0             4.0
22.0    1.0  84.0             4.0
23.0    1.0  88.0             4.0
26.0    1.0  100.0            4.0
        3.0  102.0            4.0
27.0    1.0  104.0            4.0
29.0    4.0  115.0            4.0
30.0    1.0  116.0            4.0
33.0    3.0  130.0            4.0
34.0    1.0  132.0            4.0
35.0    1.0  136.0            4.0
37.0    3.0  146.0            4.0
38.0    1.0  148.0            4.0
        3.0  150.0            4.0
39.0    1.0  152.0            4.0
        4.0  155.0            4.0
40.0    1.0  156.0            4.0
        3.0  158.0            4.0
41.0    1.0  160.0            4.0
45.0    1.0  176.0            4.0
        3.0  178.0            4.0
46.0    1.0  180.0            4.0
47.0    1.0  184.0            4.0
        2.0  185.0            4.0
        3.0  186.0            4.0
56.0    1.0  220.0            4.0
57.0    1.0  224.0            4.0
58.0    1.0  228.0            4.0
        2.0  229.0            4.0
        3.0  230.0            4.0
61.0    4.0  243.0            4.0

In [5]:
# this is det index

measure=True
beat=True
offset=False
t_sig=False
sounding=False
progress=False
lowest=False
highest=False
_all=False

cols = [df]
names = []
if _all:
    measure, beat, offset, t_sig, sounding, progress, lowest, highest = [True] * 8
if measure:
    cols.append(piece.measures().iloc[:, 0])
    names.append('Measure')
if beat:
    cols.append(piece.beatIndex())
    names.append('Beat')
if offset:
    cols.append(df.index.to_series())
    names.append('Offset')
if t_sig:
    cols.append(piece.timeSignatures().iloc[:, 0])
    names.append('TSig')
if sounding:
    cols.append(piece.soundingCount())
    names.append('Sounding')
if progress:
    prog = (df.index / piece.notes().index[-1]).to_series()
    prog.index = df.index
    cols.append(prog)
    names.append('Progress')
if lowest:
    cols.append(piece.lowLine())
    names.append('Lowest')
if highest:
    cols.append(piece.highLine())
    names.append('Highest')
temp = pd.concat(cols, axis=1)
temp2 = temp.iloc[:, len(df.columns):].ffill()
if measure:
    temp2.iloc[:, 0] = temp2.iloc[:, 0].astype(int)
mi = pd.MultiIndex.from_frame(temp2, names=names)
ret = temp.iloc[:, :len(df.columns)]
ret.index = mi
ret.dropna(inplace=True, how='all')
ret.sort_index(inplace=True)
# ret
ret

NotImplementedError: Can only union MultiIndex with MultiIndex or Index of tuples, try mi.to_flat_index().union(other) instead.

In the background we look for lyric and durational ngrams

In [6]:
lyrics = piece.lyrics()
lyrics = lyrics.applymap(piece._alpha_only)
lyr_ng = piece.ngrams(df=lyrics, n=4, exclude=[])
lyr_ng

/var/folders/_s/4t2p1z2x0yxcv068dtqj31tw0000gq/T/ipykernel_46100/3572687499.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  lyrics = lyrics.applymap(piece._alpha_only)

,Superius,Contratenor,Tenor,Bassus
0.0,"(O, gen, te, bru)","(O, gen, te, bru)","(O, gen, te, bru)","(O, gen, te, bru)"
1.0,"(gen, te, bru, net)","(gen, te, bru, net)","(gen, te, bru, net)","(gen, te, bru, net)"
2.0,"(te, bru, net, te)","(te, bru, net, te)","(te, bru, net, te)","(te, bru, net, te)"
3.0,"(bru, net, te, que)","(bru, net, te, que)","(bru, net, te, que)","(bru, net, te, que)"
4.0,"(net, te, que, Dieu)","(net, te, que, Dieu)","(net, te, que, Dieu)","(net, te, que, Dieu)"
...,...,...,...,...
254.0,NaN,NaN,NaN,"(en, ma, cham, bret)"
255.0,NaN,"(mon, aise, en, ma)","(mon, aise, en, ma)",NaN
256.0,"(en, ma, cham, bret)","(aise, en, ma, cham)","(aise, en, ma, cham)","(ma, cham, bret, te)"
258.0,"(ma, cham, bret, te)","(en, ma, cham, bret)","(en, ma, cham, bre)",NaN
260.0,NaN,"(ma, cham, bret, te)","(ma, cham, bre, te)",NaN

In [7]:
nr = piece.notes()
dur = piece.durations(df=nr)

# add ng = exclude=[] to arguments in ngrams
# specify ngram length with arguments
ng = piece.ngrams(df=dur, n=4, exclude=[])
ng

,Superius,Contratenor,Tenor,Bassus
0.0,"(1.0, 1.0, 1.0, 1.0)","(1.0, 1.0, 1.0, 1.0)","(1.0, 1.0, 1.0, 1.0)","(1.0, 1.0, 1.0, 1.0)"
1.0,"(1.0, 1.0, 1.0, 2.0)","(1.0, 1.0, 1.0, 2.0)","(1.0, 1.0, 1.0, 2.0)","(1.0, 1.0, 1.0, 2.0)"
2.0,"(1.0, 1.0, 2.0, 2.0)","(1.0, 1.0, 2.0, 2.0)","(1.0, 1.0, 2.0, 2.0)","(1.0, 1.0, 2.0, 2.0)"
3.0,"(1.0, 2.0, 2.0, 2.0)","(1.0, 2.0, 2.0, 1.0)","(1.0, 2.0, 2.0, 1.0)","(1.0, 2.0, 2.0, 3.0)"
4.0,"(2.0, 2.0, 2.0, 1.0)","(2.0, 2.0, 1.0, 2.0)","(2.0, 2.0, 1.0, 1.0)","(2.0, 2.0, 3.0, 1.0)"
...,...,...,...,...
259.0,NaN,NaN,NaN,"(1.0, 2.0, 2.0, 4.0)"
260.0,"(1.0, 1.0, 4.0, 2.0)","(2.0, 2.0, 4.0, 16.0)","(2.0, 1.0, 1.0, 4.0)","(2.0, 2.0, 4.0, 16.0)"
261.0,"(1.0, 4.0, 2.0, 16.0)",NaN,NaN,NaN
262.0,"(4.0, 2.0, 16.0, 2.0)","(2.0, 4.0, 16.0, 2.0)","(1.0, 1.0, 4.0, 16.0)","(2.0, 4.0, 16.0, 2.0)"
263.0,NaN,NaN,"(1.0, 4.0, 16.0, 2.0)",NaN

In [8]:
# hr = piece.homorhythm()
# # len(hr)
# hr = piece.emaAddresses(df=hr, mode='h')
# hr.iloc[0]['ema']

In [9]:
# now with longer ngrams

piece.homorhythm(ngram_length=4, full_hr=True).head()

                     active_voices  number_dur_ngrams  \
Measure Beat Offset
1.0     1.0  0.0               4.0                1.0
        2.0  1.0               4.0                1.0
        3.0  2.0               4.0                1.0
4.0     4.0  15.0              2.0                1.0
10.0    1.0  36.0              3.0                1.0

                                                  hr_voices  \
Measure Beat Offset
1.0     1.0  0.0     [Superius, Contratenor, Tenor, Bassus]
        2.0  1.0     [Superius, Contratenor, Tenor, Bassus]
        3.0  2.0     [Superius, Contratenor, Tenor, Bassus]
4.0     4.0  15.0                        [Superius, Bassus]
10.0    1.0  36.0              [Contratenor, Tenor, Bassus]

                                Superius          Contratenor  \
Measure Beat Offset
1.0     1.0  0.0       (O, gen, te, bru)    (O, gen, te, bru)
        2.0  1.0     (gen, te, bru, net)  (gen, te, bru, net)
        3.0  2.0      (te, bru, net, te)   (te, bru, net, te)
4.0     4.0  15.0     (ras, tu, se, ras)                  NaN
10.0    1.0  36.0                    NaN  (et, te, Sou, vent)

                                   Tenor               Bassus  \
Measure Beat Offset
1.0     1.0  0.0       (O, gen, te, bru)    (O, gen, te, bru)
        2.0  1.0     (gen, te, bru, net)  (gen, te, bru, net)
        3.0  2.0      (te, bru, net, te)   (te, bru, net, te)
4.0     4.0  15.0                    NaN   (ras, tu, se, ras)
10.0    1.0  36.0    (et, te, Sou, vent)  (et, te, Sou, vent)

                                                          syllable_set  \
Measure Beat Offset
1.0     1.0  0.0     [(O, gen, te, bru), (O, gen, te, bru), (O, gen...
        2.0  1.0     [(gen, te, bru, net), (gen, te, bru, net), (ge...
        3.0  2.0     [(te, bru, net, te), (te, bru, net, te), (te, ...
4.0     4.0  15.0             [(ras, tu, se, ras), (ras, tu, se, ras)]
10.0    1.0  36.0    [(et, te, Sou, vent), (et, te, Sou, vent), (et...

                     count_lyr_ngrams  active_syll_voices voice_match  \
Measure Beat Offset
1.0     1.0  0.0                  1.0                 4.0        True
        2.0  1.0                  1.0                 4.0        True
        3.0  2.0                  1.0                 4.0        True
4.0     4.0  15.0                 1.0                 2.0        True
10.0    1.0  36.0                 1.0                 3.0        True

                     ngram_length  Progress
Measure Beat Offset
1.0     1.0  0.0              4.0  0.000000
        2.0  1.0              4.0  0.003521
        3.0  2.0              4.0  0.007042
4.0     4.0  15.0             4.0  0.052817
10.0    1.0  36.0             4.0  0.126761

### Print the Results with Verovio

- Note that it's possible to use all of the same arguments as noted above.

In [10]:
piece.verovioHomorhythm(ngram_length=3, full_hr=True)

[Warning] Unsupported data.PERCENT '100'
[Warning] Unsupported data.PERCENT '100'
[Warning] Unsupported data.PERCENT '100'
[Warning] Unsupported data.PERCENT '100'

AttributeError: 'toolkit' object has no attribute 'setOption'

### Corpus and Homorhythm

Define the corpus list:

```
corpus_list = ['https://crimproject.org/mei/CRIM_Model_0011.mei',
              'https://crimproject.org/mei/CRIM_Model_0012.mei']
```

Import corpus:

```
corpus  = CorpusBase(corpus_list)
```

Set the length with 'ngram_length' and 'full_hr'  as True or False:

```
func = ImportedPiece.homorhythm
list_of_hr = corpus.batch(func=func, kwargs={'ngram_length' : 8, "full_hr" : True}, metadata=True)

combined_df = pd.concat(list_of_hr, ignore_index=False)
combined_df.head(10)
```

In [ ]:
corpus_list = ['https://crimproject.org/mei/CRIM_Model_0011.mei',
              'https://crimproject.org/mei/CRIM_Model_0012.mei']
corpus_list

In [ ]:
corpus  = CorpusBase(corpus_list)

In [ ]:
# set the length with 'ngram_length'
# set full_hr  as True or False

func = ImportedPiece.homorhythm
list_of_hr = corpus.batch(func=func, kwargs={'ngram_length' : 8, "full_hr" : True}, metadata=True)

combined_df = pd.concat(list_of_hr, ignore_index=False)
combined_df.head(10)

### Render HR Corpus with Verovio

Define the corpus list:

```
corpus_list = ['https://crimproject.org/mei/CRIM_Model_0011.mei',
              'https://crimproject.org/mei/CRIM_Model_0012.mei']
```
Call print function for each piece individually via 'for' loop:

```
for url in corpus_list:
    piece = importScore(url)
    piece.verovioHomorhythm(ngram_length=8, full_hr=True)
```

In [ ]:
for url in corpus_list:
    piece = importScore(url)
    piece.verovioHomorhythm(ngram_length=8, full_hr=True)