In [31]:
import requests
from IPython.display import display, HTML
from IPython.display import IFrame
import urllib.parse

import crim_intervals
from crim_intervals import * 
from crim_intervals import main_objs
import crim_intervals.visualizations as viz
import pandas as pd
import re
import altair as alt
import matplotlib.pyplot as plt
import seaborn as sns
from ipywidgets import interact
from pandas import json_normalize
from pyvis.network import Network
from IPython.display import display
import requests
import os
import glob as glob
import json
import urllib.parse


MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)
else:
    print(MYDIR, "folder already exists.")
    
MUSDIR = ("Music_Files")
CHECK_FOLDER = os.path.isdir(MUSDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MUSDIR)
    print("created folder : ", MUSDIR)
else:
    print(MUSDIR, "folder already exists.")

saved_csv folder already exists.
Music_Files folder already exists.

## Import Piece

In [32]:
prefix = 'https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/'
piece_id = 'CRIM_Model_0008.mei'

url = prefix + piece_id


piece = importScore(url)
piece.metadata

{'title': 'Ave Maria', 'composer': 'Josquin Des Prés', 'date': 1502}

In [33]:
%%capture --no-display
# piece.verovioPrintExample(10, 13)

In [34]:
prefix = 'https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/'
piece_id = 'CRIM_Model_0008.mei'
url = prefix + piece_id
piece = importScore(url)
cd=piece.cadences()
# piece.verovioCadences(df=cd)

In [35]:
p_types = piece.presentationTypes()
piece.verovioPtypes(p_types)

Results:
File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 1-7
Presentation Type:  PEN
Voices:  ['[Superius]', 'Altus', 'Tenor', 'Bassus']
Number of Entries:  4
Soggetti:  [('4', '1', '2', '2')]
Melodic Entry Intervals:  ['P-8', 'P1', 'P-8']
Time Entry Intervals:  [16.0, 16.0, 16.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

[Warning] Unsupported data.PERCENT '100'
[Warning] Unsupported data.PERCENT '100'
[Warning] Unsupported data.PERCENT '100'
[Warning] Unsupported data.PERCENT '100'
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] Unsupported '<line>' within <measure>
[Warning] 4 time pointing element(s) could not be matched in measure m-4149
[Warning] 4 time pointing element(s) could not be matched in measure m-4132
[Warning] 4 time pointing element(s) could not be matched in measure m-4098

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 8-14
Presentation Type:  PEN
Voices:  ['[Superius]', 'Altus', 'Tenor', 'Bassus']
Number of Entries:  4
Soggetti:  [('-2', '-2', '-2', '2')]
Melodic Entry Intervals:  ['P-8', 'P1', 'P-8']
Time Entry Intervals:  [16.0, 16.0, 16.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 16-22
Presentation Type:  PEN
Voices:  ['[Superius]', 'Altus', 'Tenor', 'Bassus']
Number of Entries:  4
Soggetti:  [('1', '1', '2', '2')]
Melodic Entry Intervals:  ['P-8', 'P1', 'P-8']
Time Entry Intervals:  [16.0, 16.0, 16.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 23-28
Presentation Type:  FUGA
Voices:  ['Altus', 'Bassus']
Number of Entries:  2
Soggetti:  [('-3', '-2', '2', '2')]
Melodic Entry Intervals:  ['P-8']
Time Entry Intervals:  [40.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 31-35
Presentation Type:  FUGA
Voices:  ['[Superius]', 'Tenor']
Number of Entries:  2
Soggetti:  [('1', '2', '2', '1')]
Melodic Entry Intervals:  ['P-8']
Time Entry Intervals:  [32.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 31-35
Presentation Type:  FUGA
Voices:  ['Altus', 'Bassus']
Number of Entries:  2
Soggetti:  [('3', '2', '2', '1')]
Melodic Entry Intervals:  ['P-8']
Time Entry Intervals:  [32.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 54-60
Presentation Type:  ID
Voices:  ['[Superius]', 'Altus', 'Tenor', 'Bassus']
Number of Entries:  4
Soggetti:  [('4', '-2', '2', '2')]
Melodic Entry Intervals:  ['P-5', 'P-4', 'P-5']
Time Entry Intervals:  [4.0, 36.0, 4.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 64-69
Presentation Type:  ID
Voices:  ['[Superius]', 'Altus', 'Tenor', 'Bassus']
Number of Entries:  4
Soggetti:  [('2', '-3', '2', '-3')]
Melodic Entry Intervals:  ['P-5', 'P-4', 'P-5']
Time Entry Intervals:  [16.0, 8.0, 16.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 78-81
Presentation Type:  FUGA
Voices:  ['[Superius]', 'Tenor']
Number of Entries:  2
Soggetti:  [('1', '1', '2', '-3')]
Melodic Entry Intervals:  ['P-8']
Time Entry Intervals:  [24.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 78-81
Presentation Type:  FUGA
Voices:  ['Altus', 'Bassus']
Number of Entries:  2
Soggetti:  [('1', '1', '5', '1')]
Melodic Entry Intervals:  ['P-8']
Time Entry Intervals:  [24.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 94-98
Presentation Type:  ID
Voices:  ['[Superius]', 'Tenor', '[Superius]', 'Tenor']
Number of Entries:  4
Soggetti:  [('1', '1', '2', '1')]
Melodic Entry Intervals:  ['P-5', 'P5', 'P-5']
Time Entry Intervals:  [4.0, 44.0, 4.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 111-122
Presentation Type:  ID
Voices:  ['[Superius]', 'Tenor', '[Superius]', 'Tenor']
Number of Entries:  4
Soggetti:  [('1', '1', '2', '-2')]
Melodic Entry Intervals:  ['P-8', 'P8', 'P-8']
Time Entry Intervals:  [24.0, 40.0, 24.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 127-129
Presentation Type:  FUGA
Voices:  ['[Superius]', 'Tenor']
Number of Entries:  2
Soggetti:  [('2', '2', '2', '-2')]
Melodic Entry Intervals:  ['P-8']
Time Entry Intervals:  [16.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

File Name:  CRIM_Model_0008
Josquin Des Prés
Ave Maria
Measures: 133-136
Presentation Type:  FUGA
Voices:  ['[Superius]', 'Tenor']
Number of Entries:  2
Soggetti:  [('1', '-2', '-2', '2')]
Melodic Entry Intervals:  ['P-8']
Time Entry Intervals:  [24.0]
Flexed:  False
Parallel Entries: None
Number of Non-Overlapping Voices: 0

In [36]:
prefix = 'https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/'
piece_id = 'CRIM_Model_0008.mei'
url = prefix + piece_id
piece = importScore(url)
hr = piece.homorhythm()
piece.linkExamples(df=hr, piece_url=url)

In [37]:
prefix = 'https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/'
piece_id = 'CRIM_Model_0008.mei'
url = prefix + piece_id
piece = importScore(url)
mel = piece.melodic(kind='d')
ng = piece.ngrams(df=mel, n=6, offsets='both')
piece.linkExamples(df=ng, piece_url=url)

## Ngrams and Link Example

In [42]:
prefix = 'https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/'
piece_id = 'CRIM_Model_0008.mei'
url = prefix + piece_id
piece = importScore(url)
mel = piece.melodic(kind='d')
ng = piece.ngrams(df=mel, n=6, offsets='both')
piece.linkExamples(df=ng, piece_url=url)

In [43]:
pieceurl = 'Music_Files/Daser_Missa_Ecce_nunc_Kyrie_E_corr.mei'
piece.linkExamples(df=ng, piece_url=pieceurl)

## Cadences and Linked Examples

In [44]:
cad = piece.cadences()
selected_cads = cad[cad['Tone'] == 'E']
piece.linkExamples(df=cad, piece_url=url)

## HR and Linked Examples

In [8]:
hr = piece.homorhythm(ngram_length = 4, full_hr = True).head(5)
piece.linkExamples(df=hr)

## Presentation Types and Linked Examples

In [28]:
pt = piece.presentationTypes(limit_to_entries = True,
                        head_flex=1,
                        body_flex = 0,
                        include_hidden_types = False,
                        combine_unisons = True,
                        melodic_ngram_length = 4)

In [29]:
ids = pt[pt['Presentation_Type'] == "FUGA"]

In [30]:

piece.linkExamples(df=ids)