## Presentation Type Classifier and Networks


### What can You do with this Notebook

- Find and classify imitative points (fugas, imitative duos, and periodic entries)
- Build a network of patterns found in several pieces, and reveal 'communities' of compositions


#### Network Visualization with Louvain Communities

Read more about **Louvain Community Detection Algorithms**:  https://towardsdatascience.com/community-detection-algorithms-9bd8951e7dae

**Updated Summer 2022**
**Key Features**:

- Uses `getDistance` to identify `close matches` with side-by-side comparison of soggetti.  
- For example: With a distance of "1", the soggetti `4, 1, 2, 3`, and `5, 1, 2, 3` will count as the same. These are reported as "flexed entries" in a separate column.
- Finds time intervals between entries (expressed as offsets, like `8.0, 4.0, 8.0`)
- Finds melodic intervals between first note of successive entries in each pattern (like `P-5, P-8`)
- Labels Fuga, PEn, and ID according to time intervals between entries. NIm not yet supported!
- If two entries are separated by more than 10 bars (80 offsets), the tool resets to a new pattern
- Counts number of entries
- Provides offset and measure/beat locations
- Sorts all presentation types by the order in which they appear in the piece
- Reports voice names of the entries, in order of their appearance
- Omits singleton soggetti (just one entry of a given motive in isolation)
    
- Read the documentation:  `print(piece.presentationTypes.__doc__)`

In [1]:
import crim_intervals
from crim_intervals import * 
from crim_intervals import main_objs
import crim_intervals.visualizations as viz
import pandas as pd
import re
from ipywidgets import interact
# from pandas.io.json import json_normalize
from pyvis.network import Network
from IPython.display import display
import requests
import os
import numpy as np
import itertools
from itertools import combinations
import networkx as nx
from community import community_louvain
from copy import deepcopy
import glob
MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)

else:
    print(MYDIR, "folder already exists.")

saved_csv folder already exists.

## A.  Start by Finding Presentation Types in a Corpus of Pieces 

* The **CorpusBase** class is a convenient way to find patterns in any given list of pieces.
* The pieces are provided as a **list**, within square brackets and separated by commas.  
* The bracketed list is then contained within the parentheses of `CorpusBase()`
* For example: 


```prefix = 'https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/'
piece_list = ['CRIM_Model_0019',
             'CRIM_Mass_0019_1',
             'CRIM_Mass_0019_2',
             'CRIM_Mass_0019_3',
             'CRIM_Mass_0019_4',
             'CRIM_Mass_0019_5']
suffix = '.mei'
corpus_list  = []
for piece in piece_list:
url = prefix + piece + suffix
    corpus_list.append(url)

```
Or for local files:

```

corpus_list = []
for name in glob.glob('Music_Files/*'):
    corpus_list.append(name)

```




* Read the documentation:  `print(CorpusBase.batch.__doc__)`

In [14]:
corpus_list = []
raw_prefix = "https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/"
URL = "https://api.github.com/repos/CRIM-Project/CRIM-online/git/trees/990f5eb3ff1e9623711514d6609da4076257816c"
piece_json = requests.get(URL).json()

# list of files to exclude

# exclude_list = ['CRIM_Model_0003.mei', 'CRIM_Model_0004.mei', 'CRIM_Model_0005.mei', 'CRIM_Model_0006.mei', 
#              'CRIM_Model_0007.mei',
#             'CRIM_Model_0022.mei', 'CRIM_Model_0028.mei', 'CRIM_Model_0035.mei', 'CRIM_Mass_0029_4.mei', 
#              'CRIM_Mass_0049_2.mei',
#             'CRIM_Mass_0049_5.mei']

exclude_list = ['CRIM_Mass_0004_3.mei', 
                'CRIM_Mass_0022_2.mei',
                'CRIM_Mass_0033_2.mei',
                'CRIM_Mass_0033_3.mei',
                'CRIM_Mass_0033_4.mei',
                'CRIM_Mass_0033_5.mei',
                'CRIM_Mass_0048_5.mei',
               'CRIM_Model_0003.mei',
                'CRIM_Model_0004.mei',
                'CRIM_Model_0005.mei',
                'CRIM_Model_0006.mei',
                'CRIM_Model_0007.mei',
                'CRIM_Model_0022.mei',
                'CRIM_Model_0028.mei',
                'CRIM_Model_0030.mei',
                'CRIM_Model_0035.mei',
                'CRIM_Model_0034.mei',
                'CRIM_Model_0044.mei',
                'CRIM_Model_0041.mei'
               ]

# this ensures that we don't try to analyze the 'Mass head only' files, which have no musical content

pattern = 'CRIM_Mass_([0-9]{4}).mei'

# and now the request for all the files
for p in piece_json["tree"]:
    p_name = p["path"]
    if re.search(pattern, p_name):
        pass
    elif p_name in exclude_list:
        pass
    else:
        corpus_list.append(raw_prefix + p["path"])

In [8]:
# corpus_list

In [88]:
# only if loading local files
corpus_list = []
for name in glob.glob('Music_Files/*'):
    corpus_list.append(name)

In [4]:
pd.set_option('future.no_silent_downcasting', True)

In [5]:
len(corpus_list)

256

### Now Run the PresentationType method on the Corpus

In [15]:
# This will need to be modified if using a corpus method different from the CRIM Project above.
final = pd.DataFrame()

list_dfs = []

for work in corpus_list[0:260]:
    print(work)

    piece = importScore(work, verbose=True)   
    output = piece.presentationTypes(limit_to_entries = True,
                                     head_flex = 1,
                                     body_flex = 0,
                                     include_hidden_types = False,
                                     combine_unisons = True,
                                     melodic_ngram_length = 4)

    if output is not None:
        list_dfs.append(output)
final = pd.concat(list_dfs, ignore_index=True)
final

# final.to_csv("corpus_classified.csv")
# final.to_csv("saved_csv/CRIM_Mass_0019_P_Types_hidden.csv")

https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0001_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0001_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0001_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0001_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0001_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0002_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0002_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0002_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0002_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0002_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0003_1.mei
Previously imported piece detected.
No Presentation Types Found in Nicolas De Marle:Missa O gente brunette: Kyrie
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0003_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0003_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0003_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0003_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0004_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0004_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0004_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0004_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0005_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0005_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0005_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0005_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0005_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0006_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0006_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0006_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0006_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0006_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0007_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0007_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0007_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0007_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0007_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0008_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0008_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0008_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0008_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0008_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0009_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0009_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0009_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0009_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0009_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0010_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0010_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0010_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0010_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0010_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0011_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0011_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0011_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0011_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0011_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0012_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0012_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0012_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0012_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0012_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0013_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0013_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0013_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0013_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0013_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0014_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0014_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0014_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0014_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0014_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0015_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0015_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0015_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0015_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0015_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0016_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0016_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0016_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0016_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0016_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0017_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0017_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0017_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0017_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0017_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0018_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0018_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0018_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0018_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0018_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0019_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0019_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0019_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0019_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0019_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0020_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0020_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0020_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0020_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0020_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0021_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0021_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0021_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0021_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0021_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0023_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0023_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0023_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0023_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0023_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0024_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0024_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0024_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0024_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0024_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0025_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0025_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0025_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0025_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0025_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0026_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0026_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0026_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0026_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0026_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0027_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0027_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0027_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0027_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0027_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0028_1.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0028_2.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0028_3.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0028_4.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0028_5.mei
Previously imported piece detected.
https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/CRIM_Mass_0029_1.mei
Previously imported piece detected.

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps,Progress
0,Pierre Colin,Missa Confitemini: Kyrie,88.0,"[11.0/1.0, 11.0/4.0, 12.0/1.0, 13.0/1.0]","[P-4, P-5, P12]","[88.0, 94.0, 96.0, 104.0]","[(-2, 2, 2, -2), (-3, 2, 2, -2)]","[6.0, 2.0, 8.0]","[Contratenor, Tenor, Bassus, Superius]",FUGA,4,True,False,None,0,0.372881
1,Pierre Colin,Missa Confitemini: Kyrie,176.0,"[21.0/1.0, 23.0/2.0, 25.0/4.0]","[P1, P-4]","[176.0, 194.0, 214.0]","[(5, -3, 2, 2), (4, -3, 2, 2)]","[18.0, 20.0]","[Tenor, Bassus, Bassus]",FUGA,3,True,False,None,1,0.745763
2,Pierre Colin,Missa Confitemini: Gloria,0.0,"[1.0/1.0, 6.0/4.0, 7.0/2.0]","[P-5, P5]","[0.0, 46.0, 50.0]","[(3, -2, -3, 2)]","[46.0, 4.0]","[Contratenor, Bassus, Tenor]",FUGA,3,False,False,None,0,0.000000
3,Pierre Colin,Missa Confitemini: Gloria,146.0,"[19.0/2.0, 23.0/2.0]",[m3],"[146.0, 178.0]","[(-3, 2, 2, 2)]",[32.0],"[Tenor, Contratenor]",FUGA,2,False,False,None,0,0.218563
4,Pierre Colin,Missa Confitemini: Gloria,238.0,"[30.0/4.0, 31.0/2.0]",[P5],"[238.0, 242.0]","[(-2, -3, 2, 2)]",[4.0],"[Bassus, Tenor]",FUGA,2,False,False,None,0,0.356287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3333,Jacob Clemens non Papa,Entre vous filles,0.0,"[1.0/1.0, 2.0/3.0]",[P-8],"[0.0, 12.0]","[(-2, -2, -2, 2)]",[12.0],"[Contratenor, Bassus]",FUGA,2,False,False,None,0,0.000000
3334,Jacob Clemens non Papa,Entre vous filles,0.0,"[1.0/1.0, 2.0/3.0]",[P-8],"[0.0, 12.0]","[(3, 3, -2, -2)]",[12.0],"[Superius, Tenor]",FUGA,2,False,False,None,0,0.000000
3335,Jacob Clemens non Papa,Entre vous filles,20.0,"[3.0/3.0, 5.0/3.0, 7.0/3.0, 13.0/1.0]","[P-8, P8, P-8]","[20.0, 36.0, 52.0, 96.0]","[(-2, -2, -2, 3)]","[16.0, 16.0, 44.0]","[Superius, Tenor, Superius, Tenor]",FUGA,4,False,False,None,0,0.076923
3336,Jacob Clemens non Papa,Entre vous filles,24.0,"[4.0/1.0, 6.0/1.0]",[P-8],"[24.0, 40.0]","[(-2, -2, -2, -2)]",[16.0],"[Contratenor, Bassus]",FUGA,2,False,False,None,0,0.092308
3337,Roland de Lassus,Domine Dominus noster,0.0,"[1.0/1.0, 7.0/2.0]",[P4],"[0.0, 50.0]","[(-2, 2, -3, 2)]",[50.0],"[Altus, Sexta]",FUGA,2,False,False,None,1,0.000000

In [94]:
final

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps,Progress
0,Pierre Colin,Missa Confitemini: Kyrie,88.0,"[11.0/1.0, 11.0/4.0, 12.0/1.0, 13.0/1.0]","[P-4, P-5, P12]","[88.0, 94.0, 96.0, 104.0]","[(-2, 2, 2, -2), (-3, 2, 2, -2)]","[6.0, 2.0, 8.0]","[Contratenor, Tenor, Bassus, Superius]",FUGA,4,True,False,None,0,0.372881
1,Pierre Colin,Missa Confitemini: Kyrie,176.0,"[21.0/1.0, 23.0/2.0, 25.0/4.0]","[P1, P-4]","[176.0, 194.0, 214.0]","[(5, -3, 2, 2), (4, -3, 2, 2)]","[18.0, 20.0]","[Tenor, Bassus, Bassus]",FUGA,3,True,False,None,1,0.745763
2,Pierre Colin,Missa Confitemini: Gloria,0.0,"[1.0/1.0, 6.0/4.0, 7.0/2.0]","[P-5, P5]","[0.0, 46.0, 50.0]","[(3, -2, -3, 2)]","[46.0, 4.0]","[Contratenor, Bassus, Tenor]",FUGA,3,False,False,None,0,0.000000
3,Pierre Colin,Missa Confitemini: Gloria,146.0,"[19.0/2.0, 23.0/2.0]",[m3],"[146.0, 178.0]","[(-3, 2, 2, 2)]",[32.0],"[Tenor, Contratenor]",FUGA,2,False,False,None,0,0.218563
4,Pierre Colin,Missa Confitemini: Gloria,238.0,"[30.0/4.0, 31.0/2.0]",[P5],"[238.0, 242.0]","[(-2, -3, 2, 2)]",[4.0],"[Bassus, Tenor]",FUGA,2,False,False,None,0,0.356287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,Antoine de Févin,Missa Ave Maria: Kyrie,304.0,"[38.0/1.0, 42.0/1.0, 45.0/2.0, 50.0/4.0, 52.0/...","[P-8, P5, P-8, P8, P-8, P8, P1, P8]","[304.0, 336.0, 362.0, 406.0, 418.0, 454.0, 458...","[(-2, -2, -2, 2)]","[32.0, 26.0, 44.0, 12.0, 36.0, 4.0, 20.0, 4.0]","[Sup[erius], Tenor, Altus, Bassus, Altus, Bass...",FUGA,9,False,False,None,0,0.391753
181,Antoine de Févin,Missa Ave Maria: Kyrie,528.0,"[65.0/1.0, 67.0/1.0, 69.0/1.0, 71.0/1.0]","[P-8, P12, P-8]","[528.0, 544.0, 560.0, 576.0]","[(2, 2, -3, 3)]","[16.0, 16.0, 16.0]","[Altus, Bassus, Sup[erius], Tenor]",PEN,4,False,False,None,0,0.680412
182,Antoine de Févin,Missa Ave Maria: Kyrie,596.0,"[73.0/3.0, 77.0/3.0]",[P8],"[596.0, 628.0]","[(-3, -2, 2, 2)]",[32.0],"[Bassus, Altus]",FUGA,2,False,False,None,0,0.768041
183,Antoine de Févin,Missa Ave Maria: Kyrie,672.0,"[83.0/1.0, 88.0/3.0, 89.0/3.0, 91.0/1.0]","[P1, P1, P8]","[672.0, 716.0, 724.0, 736.0]","[(-3, -2, 4, 2)]","[44.0, 8.0, 12.0]","[Tenor, Altus, Tenor, Sup[erius]]",FUGA,4,False,False,None,1,0.865979
184,Antoine de Févin,Missa Ave Maria: Kyrie,702.0,"[86.0/4.0, 94.0/4.0]",[P8],"[702.0, 766.0]","[(-2, -2, -2, 2)]",[64.0],"[Tenor, Sup[erius]]",FUGA,2,False,False,None,1,0.904639

## Various Options to Filter to Prepare to Network

See the Presentation Type Filter Notebook for more ideas!

But the results of this filtering are needed to make useful networks below!

* by type
* by piece
* according to length between entries

In [67]:
# filter for only ID or PEN
pen_id_filter = final['Presentation_Type'].isin(["PEN"])
pen_id_only = final[pen_id_filter]
final = pen_id_only.copy()
len(final)

19

## B. Network Visualization with Louvain Communities

* This will only make sense for a corpus!

## Add Combined Data for Melodic, Time and Soggetti as "Words" for Network Edges

- We combine the lists of time and melodic intervals of entries as strings (thus a kind of word that uniquely identifies that pattern)
- We do the same for soggetti, combining the melodic intervals themselves as a string
- These are in turn assembled in various combinations:  TINT, MINT, and SOG, also as strings

In [16]:
final["MINT"] = final["Melodic_Entry_Intervals"].apply(joiner)
final["TINT"] = final["Time_Entry_Intervals"].apply(joiner)

final['SOG'] = final['Soggetti'].apply(clean_melody_new)
final['ALL'] = final["MINT"] + '_' + final["TINT"] + '_' + final['SOG']

final["ALL_INT"] = final["MINT"] + '_' + final["TINT"]
final["MINT_SOG"] = final["MINT"] + '_' + final["SOG"]
final["TINT_SOG"] = final["TINT"] + '_' + final["SOG"]
final.head()

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,...,Parallel_Voice,Count_Non_Overlaps,Progress,MINT,TINT,SOG,ALL,ALL_INT,MINT_SOG,TINT_SOG
0,Pierre Colin,Missa Confitemini: Kyrie,88.0,"[11.0/1.0, 11.0/4.0, 12.0/1.0, 13.0/1.0]","[P-4, P-5, P12]","[88.0, 94.0, 96.0, 104.0]","[(-2, 2, 2, -2), (-3, 2, 2, -2)]","[6.0, 2.0, 8.0]","[Contratenor, Tenor, Bassus, Superius]",FUGA,...,None,0,0.372881,P-4_P-5_P12,6.0_2.0_8.0,-2_2_2_-2,P-4_P-5_P12_6.0_2.0_8.0_-2_2_2_-2,P-4_P-5_P12_6.0_2.0_8.0,P-4_P-5_P12_-2_2_2_-2,6.0_2.0_8.0_-2_2_2_-2
1,Pierre Colin,Missa Confitemini: Kyrie,176.0,"[21.0/1.0, 23.0/2.0, 25.0/4.0]","[P1, P-4]","[176.0, 194.0, 214.0]","[(5, -3, 2, 2), (4, -3, 2, 2)]","[18.0, 20.0]","[Tenor, Bassus, Bassus]",FUGA,...,None,1,0.745763,P1_P-4,18.0_20.0,5_-3_2_2,P1_P-4_18.0_20.0_5_-3_2_2,P1_P-4_18.0_20.0,P1_P-4_5_-3_2_2,18.0_20.0_5_-3_2_2
2,Pierre Colin,Missa Confitemini: Gloria,0.0,"[1.0/1.0, 6.0/4.0, 7.0/2.0]","[P-5, P5]","[0.0, 46.0, 50.0]","[(3, -2, -3, 2)]","[46.0, 4.0]","[Contratenor, Bassus, Tenor]",FUGA,...,None,0,0.000000,P-5_P5,46.0_4.0,3_-2_-3_2,P-5_P5_46.0_4.0_3_-2_-3_2,P-5_P5_46.0_4.0,P-5_P5_3_-2_-3_2,46.0_4.0_3_-2_-3_2
3,Pierre Colin,Missa Confitemini: Gloria,146.0,"[19.0/2.0, 23.0/2.0]",[m3],"[146.0, 178.0]","[(-3, 2, 2, 2)]",[32.0],"[Tenor, Contratenor]",FUGA,...,None,0,0.218563,m3,32.0,-3_2_2_2,m3_32.0_-3_2_2_2,m3_32.0,m3_-3_2_2_2,32.0_-3_2_2_2
4,Pierre Colin,Missa Confitemini: Gloria,238.0,"[30.0/4.0, 31.0/2.0]",[P5],"[238.0, 242.0]","[(-2, -3, 2, 2)]",[4.0],"[Bassus, Tenor]",FUGA,...,None,0,0.356287,P5,4.0,-2_-3_2_2,P5_4.0_-2_-3_2_2,P5_4.0,P5_-2_-3_2_2,4.0_-2_-3_2_2

### Make Groups, Based on Selected Criteria:

* MINT (the melodic intervals between imitative entries)
* TINT (the time intervals between imitative entries)
* SOG (the soggetti)
* Or any of the combinations:
    * ALL (MINT + TINT + Soggetti)
    * ALL_INT (MINT + TINT)
    * MINT_SOG (MINT + Soggetti)
    * TINT_SOG (TINT + Soggetti)

In [120]:

output_grouped = final.groupby(['MINT'])['Title'].apply(list).reset_index()
output_grouped

,MINT,Title
0,M-10,[Missa Voulant honneur: Sanctus]
1,M-13,[Missa Baisiez moy: Kyrie]
2,M-2,"[Missa Confitemini: Credo, Missa Confitemini: ..."
3,M-2_P-4_P12_M-9,[Missa Vidi speciosam: Gloria]
4,M-2_P5,[Missa Tota pulchra es: Kyrie]
...,...,...
447,m7_M2,[Missa Benedicta es: Sanctus]
448,m7_P-5,[Missa Voulant honneur: Agnus Dei]
449,m7_P-8,[Missa Quare fremuerunt gentes: Agnus Dei]
450,m7_P1,[Missa Benedicta es: Credo]
451,m7_m-3_P-5_M9_P-12_P8_P-5,[Missa Benedicta es: Gloria]

## Group and Find Unique Pairs

- the pairing must be applied to columns that have more than one value, like Title, since these form the edges

In [105]:
pairs = output_grouped.Title.apply(lambda x: list(combinations(x, 2)))
pairs2 = pairs.explode().dropna()
unique_pairs = pairs.explode().dropna().unique()
len(unique_pairs)

633

In [18]:
# define network functions.  Do not edit!

def add_communities(G):
    G = deepcopy(G)
    partition = community_louvain.best_partition(G)
    nx.set_node_attributes(G, partition, "group")
    return G

def create_node_html(node: str, 
                     source_df: pd.DataFrame, 
                     node_col: str):
    rows = source_df.loc[source_df[node_col] == node].itertuples()
    
    html_lis = []
    
    for r in rows:
        html_lis.append(f"""<li>Composer: {r.Composer}<br>
                                Title: {r.Title}<br>
                                """
                       )
        
    html_ul = f"""<ul>{''.join(html_lis)}</ul>"""
        
    return html_ul


def add_nodes_from_edgelist(edge_list: list, 
                               source_df: pd.DataFrame, 
                               graph: nx.Graph,
                               node_col: str):
    
    graph = deepcopy(graph)
    
    node_list = pd.Series(edge_list).apply(pd.Series).stack().unique()
    
    for n in node_list:
        graph.add_node(n, 
                       title=create_node_html(n, source_df, node_col))
        
    return graph

def choose_network(df, chosen_word, file_name):
    
    if len(df) < 1:
        print("Sorry, No P Types to display")
    else:
        output_grouped = df.groupby(['MINT'])[chosen_word].apply(list).reset_index()
        pairs = output_grouped[chosen_word].apply(lambda x: list(combinations(x, 2)))
        pairs2 = pairs.explode().dropna()
        unique_pairs = pairs.explode().dropna().unique()
        # print(unique_pairs)


        pyvis_graph = Network(notebook=True, 
                              width="1800", 
                              height="1400", 
                              bgcolor="black", 
                              font_color="white")
        pyvis_graph.set_options("""
                            {
                            "physics": {
                            "enabled": true,
                            "forceAtlas2Based": {
                                "springLength": 1
                            },
                            "solver": "forceAtlas2Based"
                            }
                            }
                            """)
        G = nx.Graph()

        try:
            G = add_nodes_from_edgelist(edge_list=pairs2, 
                                        source_df=final, 
                                        graph=G, 
                                        node_col=chosen_word)
        except Exception as e:
            print(e)


        G.add_edges_from(unique_pairs)
        G = add_communities(G)
        pyvis_graph.from_nx(G)
        pyvis_graph.show(file_name)

In [107]:
# Find your rendered network in the Jupyter Hub file list!

choose_network(final, 'Title', 'Mod_Mass_Full_Sog_19.html')

In [108]:
chosen_word = 'Title'
output_grouped = final.groupby(['ALL_INT'])[chosen_word].apply(list).reset_index()
pairs = output_grouped[chosen_word].apply(lambda x: list(combinations(x, 2)))
pairs[0:3]

0                                                   []
1                                                   []
2    [(Missa Ave Maria: Credo, Missa Ave Maria: Cre...
Name: Title, dtype: object

In [19]:
chosen_word = 'Title'
output_grouped = final.groupby(['MINT_SOG'])[chosen_word].apply(list).reset_index()
pairs = output_grouped[chosen_word].apply(lambda x: list(combinations(x, 2)))


pairs2 = pairs.explode().dropna()

    
# print(unique_pairs)


pyvis_graph = Network(notebook=True, 
                      width="1800", 
                      height="1400", 
                      bgcolor="black", 
                      font_color="white")
pyvis_graph.set_options("""
                    {
                    "physics": {
                    "enabled": true,
                    "forceAtlas2Based": {
                        "springLength": 1
                    },
                    "solver": "forceAtlas2Based"
                    }
                    }
                    """)
G = nx.Graph()

try:
    G = add_nodes_from_edgelist(edge_list=pairs2, 
                                source_df=final, 
                                graph=G, 
                                node_col='Title')
except Exception as e:
    print(e)


G.add_edges_from(pairs2)
G = add_communities(G)
pyvis_graph.from_nx(G)
pyvis_graph.show('test.html')